### ISSUE TITLE
As a user of the NISV RDF schema, I want to understand the meaning of the properties

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#10]
- [x] Translate the existing metadata dictionary comments to English
- [x] Create comments for the classes and add to the metadata dictionary
- [x] Add these class comments manually to the schema
- [ ] Add user-friendly labels to all the properties in the metadata dictionary

An automatic update process to allow all the content of the metadata dictionary to be written to the schema will be tackled in #21.

**Comment by jblom** [comment]
@mwigham can't this not be simply expressed (and edited) in triples? The end-result would be a bunch of queries that can update the descriptions. In the accompanying documentation you can publish the queries + a link to the SPARLQ editor or something. What do you think?

**Comment by mwigham** [comment]
Certainly possible, I'd just assumed people would be more comfortable with an Excel.

**Comment by jblom** [comment]
so the Excel could be occasionally updated via a script that queries the triplestore. I assume you don't want users to update these descriptions right?

**Comment by mwigham** [comment]
The Excel wouldn't be for users, but for NISV to input and edit the descriptions. It would be nice if we have just one source of descriptions for both the Media Suite and the RDF schema.

**Comment by mwigham** [comment]
This issue is now purely about making sure we have comments for all properties and classes. How we then update these with new versions will be tackled in a separate issue

**Comment by jblom** [comment]
@mwigham assigned this story to the new sprint, so it can be properly finalised there

**Comment by wmelder** [comment]
I would suggest to represent the schema in HTML for humans, including human readable labels and basic, but awesome styling.

**Comment by jblom** [comment]
@wmelder @mwigham yeah I would also prefer showing & editing via a clean & simple HTML page. Much easier to maintain and close to the web, which LD is all about. I'm sure there are already solutions for this (Rob de Zeeuw from Meertens was working on something like this), but it should be quite simple to setup a page like this ourselves.

**Comment by mwigham** [comment]
@lilimelgar are the labels complete now? If so, we can close this issue

@jblom @wmelder Good idea to have the schema in a HTML representation, I'll create an issue for that. I'm less convinced we should perform all edits in this representation, but it's open for discussion

**Comment by jblom** [comment]
@lilimelgar closing this, since it's only a matter of updating the CKAN sheet and finally updating production
