### ISSUE TITLE
Task: extend the daan to schema mapping with showbrowse

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#118]
"match": {
"payload.nisv.showbrowse.value": "true"
}
currently op programs in flexstore => 
"hits": {
"total": 36478,

deze programs mogen getoond worden in de GPP, bijv. https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101811140250154131
voor dit voorbeeld zie ik echter geen afspeelbare media in de gpp
Deze heeft dat wel: https://zoeken.beeldengeluid.nl/program/urn:vme:default:program:2101808210248811431

mogelijk heeft dit veld er ook nog mee te maken (eventueel filteren?):
"aclGroups": [
{
"name": "NISV_BROWSE",
"read": "1",
"write": "1",
"nameRead": "NISV_BROWSE_1"
}

Voor series en seasons moet de URL aangepast worden: bijv. https://zoeken.beeldengeluid.nl/series/urn:vme:default:series:2101712140234422531

**Comment by wmelder** [comment]
de flex datastore url http://prd-es-bng-01.beeldengeluid.nl/head/?base_uri=/es
de query 
"query": {
"bool": {
"must": [
{
"match": {
"payload.nisv.showbrowse.value": "true"
}
}
],
"must_not": [ ],
"should": [ ]
}
},
"from": 0,
"size": 10,
"sort": [ ],
"aggs": { }

**Comment by wmelder** [comment]
uit m ail Time: Voor het afspelen van media is het veld show browse GPP belangrijk. 
query is: nisv.showbrowse@program:true

Dit is soms ook materiaal waarvoor bij een download wel een licentie vereist is (bv. vanwege ethische checks, dusws. wil je ook de dictionarywaarde uit het veld nisv.licensecondition@program opnemen in de sets.

**Comment by wmelder** [comment]
en ook uit mail tim: Overige belangrijke velden / queries zijn nog: 
(Publiek domein, weesje of vrijgegeven) 

precook.nisv.rightslicense:5 OR precook.nisv.rightslicense: 206 OR precook.nisv.rightslicense: 204 OR nisv.iprcombined@program: 4 OR nisv.iprcombined@program: 205 OR  nisv.iprcombined@program: 206 

EN
nisv.licensecondition@program: CC-BY OR nisv.licensecondition@program: CC-BY-NC OR nisv.licensecondition@program: CC-BY-NC-ND OR CC-BY-NC-SA OR nisv.licensecondition@program: CC-BY-ND OR nisv.licensecondition@program: CC-BY-SA

**Comment by mwigham** [comment]
@wmelder Sorry, but I don't understand this issue. The title suggests it is to add showbrowse to the mapping, but the comments above seem to be related to the GPP link, which is covered by another issue. Could you describe what work should be done in this issue please?

**Comment by wmelder** [comment]
@mwigham This issue is meant to be about adding showbrowse to the mapping. Because it was not clear yet how this works with the poprtal etc. there might be some redundant text. So, the gpp link is already taken care of in another issue (but not for season), but the showbrowse value should be added.

**Comment by mwigham** [comment]
Thanks @wmelder. Do you think we want to actually include showbrowse in the output data, or is it just information that we need in the logic for creating the GPP link? If the latter then I won't map it but will make sure the value is made available to assist in making the link.

**Comment by wmelder** [comment]
@mwigham It is solely the purpose that we include it in the output data so that users can filter on it. If they only want to use metadata about stuff that is playable on the portal this is a necessary property. It minimizes the risc of disappointments when people search for something and think they find it, but then the door is locked.

**Comment by mwigham** [comment]
Ok, so we link to the portal no matter what and include information about playability to let the user choose themselves if that is important to them or not.

**Comment by wmelder** [comment]
I think the easiest thing to do is to use:
https://schema.org/conditionsOfAccess

Since this field assumes a text message from the archival institute we can put in a message like: "Showbrowse is true/false"

Variations on that message:
"Playable and/or viewable in the General Public Portal. See the item's URL."
"Media is available at the General Public Portal vai the URL of the item."
"This item's metadata is available at the GPP, but the media is not accessible."
"Media can be played/viewed at URL."
"Media is not shown in the Genral Public Portal."
or, simply:
"Media available in GPP: True/False"

How does that sound as a pragmatic solution?

**Comment by wmelder** [comment]
There is a message at schema.org saying that we can provide feedback on this property, before it is adopted in the standard:
"This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites."
We might consider if we have a need for more properties, or advice on this property.

**Comment by mwigham** [comment]
I think this field gives us the most freedom to accurately describe it. The only practical disadvantage is that users wanting to filter for playable content will have to check the text in their SPARQL queries. We could consider only filling in this field if the content is playable, as then all they need to do is check if the property is present, but this may be confusing for users. In any case we should ensure the text is always identical, so they can check with == rather than having to worry about regex.

**Comment by wmelder** [comment]
if we only fill it when showbrowse is true, then a SPARQL FILTER EXISTS  suffices to filter out the result sets. On the other hand, if we don't fill the cases when the showbrowse is False, we don't make it explicit that is is not playable (and we know that in advance). A SPARQL FILTER (CONTAINS(conditionOfAccess, 'True' ) would be enough to filter, if we model the field like: "Media available in GPP: True/False". So the latter option would probably be better from a publication point of view. The former option would probably be preferred from a SPARQL client perspective. 

Since we are the publisher I am inclined to say that we need to fill the field always.

**Comment by mwigham** [comment]
Sounds good. I would suggest we extend the text a little though as even beng colleagues often don't know what the GPP is ;). E.g.:
 "Media playable in the General Public Portal: True. See the item's URL."

Perhaps we can even make it that we only add 'See the item's URL' when the value is True.

The nice side of your idea to use 'contains' is that we can still improve the text later. We should make that clear in the documentation (once we write some).

**Comment by wmelder** [comment]
I think showbrowse was added, so this issue can be closed
