### ISSUE TITLE
As a developer, I want to generate RDF data for the NISV archive that uses the GTAA thesaurus terms

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#12]
The goal of this story is to adapt the code for generating RDF data to show the values of the metadata fields as GTAA concepts

**Acceptance criteria**
- [ ] implement a method/approach for matching & mapping metadata fields to GTAA concepts
- [ ] implement a statistic for the completeness of the resulting mapped GTAA concepts

**Comment by jblom** [comment]
@wmelder @mwigham please check the acceptance criteria again. Anyway I've put this in the backlog, but at the very bottom, since it is not required for V4. (the backlog from now on reflects the work that should be done for V4. The rest is put in the icebox brrr)

**Comment by mwigham** [comment]
@wmelder can we close this? You've implemented matching for our current data, and for the DAAN data the matching is not necessary.

**Comment by wmelder** [comment]
@ mwigham  Sure! The main problem now is still the size of the data and loading it, not so much the matching. The current lod-importer contains a module that matches the old NISV immix data with the imported GTAA conceptSchemes. The matching can be done using SPARQL update in a reasonable time. So far, only the smallest conceptSchemes have been tested and only for catalogs that were not huge, but also not small. like journaal.  For DAAN the GTAA identifiers are already included by the daan2rdf transformers you are working on. The completeness metric mentioned in the issue description is not ready, I guess..

**Comment by mwigham** [comment]
Do we still need a completeness metric given that there is no matching needed for DAAN? If it is incomplete, then that is due to the data not being present in DAAN. Is that of interest?

**Comment by wmelder** [comment]
if you think not than better close this story.
