### ISSUE TITLE
fix: sdo:additionalType in query not available in NISV modelled data

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#121]
Please make sure that the code also works for the NISV schema.
the pain is in [this line](https://github.com/beeldengeluid/beng-lod-server/blob/e0d494affdb46e81ace64f13ba781a678fc60f48/src/apis/lod/DAANSchemaImporter.py#L68-L69):

The error message indicates SDO is not known. This is probably because it is not used in the NISV handler
    raise Exception('Unknown namespace prefix : %s' % prefix)
Exception: Unknown namespace prefix : sdo

**Comment by wmelder** [comment]
maybe it helps to add the schema prefix to daan-mapping-storage.ttl

**Comment by wmelder** [comment]
I pushed a fix.

**Comment by wmelder** [comment]
@mwigham Can you have a look at the fix? Is it complete or do we still miss something. If it is fit for purpose, can put this issue to Done?

**Comment by mwigham** [comment]
That is fine, as the only need for the sdo prefix in this case is to allow the query in the importer to work. 

As a note for the future, if we wanted to actually use sdo in the output data, then we would need to add it to the namespace manager of the graph in the relevant **RdfConcept.py file, as is done in SDORdfConcept.py

**Comment by wmelder** [comment]
We might try to use @vocab for schema.org. But it needs to be tested if things don't fail, because of a default namespace.

**Comment by wmelder** [comment]
since this issue is labeled as bug and that bug was fixed, close this one.
