### ISSUE TITLE
As a developer, I want the NISV RDF schema to reflect the new DAAN model

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#13]
Adapt the RDF schema to reflect the new DAAN model, where that is useful for users of linked data

**Acceptance criteria**
- [x] make sure to setup a web representation that can be easily updated for frequent demoing sharing with colleagues that can provide relevant input
- [x] ensure that the model remains concise and avoid meaningless layers/relations that have no meaning to a user; keep user/system friendly queries in mind
- [x] document the decisions made for this first version, in particular what is and isn't included
- [ ] make sure to consult with DAAN experts & catalogue experts, but don't wait for everything to be perfect

**Comment by jblom** [comment]
@mwigham @wmelder also in backlog with added acceptance criteria. Please refine as you see fit

**Comment by mwigham** [comment]
I have created a separate issue #53 for how we can model the locations (carrier and timing information) of the various content and enrichments of a program in such a way that we can abstract from the physical storage implementation (which is dominant in the DAAN model). For now, I suggest we concentrate on the descriptive metadata, so leave out the details of timing on carriers (and leave out enrichments altogether). In this way, we can leave tackling the complexity of aggregate assets, segments and technical logtrack items until later.

**Comment by mwigham** [comment]
Will document the selection process in the wiki

**Comment by mwigham** [comment]
The first version is complete, checked in in the daan-schema branch of beng-lod-server. It is documented [here](https://github.com/beeldengeluid/beng-lod-server/wiki/DAAN-RDF-Schema). We can view a web representation either with [Eduardo's code](https://github.com/beeldengeluid/beng-lod-server/issues/31) or using [ontospy](https://pypi.org/project/ontospy/). I suggest we make consultation with experts an on-going thing, so that we have regular iterations of improving the schema, discussing it, testing it and specifying new improvements. We can do a first session to discuss this version of the schema, or we can wait until we've transformed some data using the schema, to have examples to look at and also to detect any technical issues. @wmelder @jblom , which do you prefer?

**Comment by mwigham** [comment]
@wmelder @jwassenaarbg could you review please? The steps are:

- [ ] Read the [documentation](https://github.com/beeldengeluid/beng-lod-server/wiki/DAAN-RDF-Schema) and see if you agree with the excluded metadata fields
- [ ] Check out the [schema](https://github.com/beeldengeluid/beng-lod-server/blob/daan-schema/resource/bengSchema.ttl)
- [ ] As Eduardo's code is based on the iMMIx version of the schema, install ontospy `pip install ontospy[FULL] -U` (note, for me it didn't work via pipenv, it complained about the '-U' option)
- [ ] Generate a HTML view of the schema `ontospy gendocs <location of bengSchema.ttl>`, choosing option 2
- [ ] Browse the schema, looking at whether we have everything included that we want, and if the structure seems reasonable (which properties are on which classes etc.). Don't worry about the details of names and comments, we will look at that later with metadata experts, this is just a first version of the schema.

**Comment by wmelder** [comment]
issues: 
- according to the schema an 'afspeelbaar audiovisueel object' is a skos:concept. should not be like that. I think, what was meant is that the 'playable AV object' has properties that are skos:concepts.
- the use of multiple languages for the labels must be consequent. Thus, all properties and classes must be defined both in 'nl' and 'en'. This is also necessary for the HTML schema representation to be multilingual.


observations:
-  the full schema is a class hierarchy visualisation. no properties are present. since the carrier information now seems to be included in the 'afspeelbare audiovisueel object' it has dropped completely from the class diagram. => make sure the properties are listed in the HTML representation. 
- eduardo's HTML representation should also work on the DAAN RDF. It seems like a good thing to have both Eduardo's HTML and ontospy's HTML, since the first also llists properties and the second includes some diagrams that are very nice to get insight into the class relations. => TODO: branch 'daan-schema' needs to be merged with 'issues/# 31' and the ontospy code needs to be included. 

- to be continued...

**Comment by mwigham** [comment]
Thanks for the review!
I've removed the 'is a skos:Concept' for PlayableAudiovisualObject, this was indeed an error.
Language use definitely needs to be consistent, and Eduardo's overview will be essential in being able to ensure that, as it makes it easy to see what is missing. I thought I had created an issue for making all labels fully complete, but I can't find it at the moment, so I'll create a new one.

Regarding the observations:
Yes, the image is only the class hierarchy, as that is all I can export from Protege. Again a good use for Eduardo's code
I agree, the two representations are complementary, and it's a big bonus that we can tweak our own code to our exact needs
Perhaps you could suggest what the essential basic information would be for rights? Then we can make sure we get this.

Thanks for the further comments, I'll address those in the spreadsheet.

Is this issue now ready to be closed?

**Comment by wmelder** [comment]
@mwigham ready to close. the following tasks have to be done in another issue.

- As Eduardo's code is based on the iMMIx version of the schema, install ontospy pip install ontospy[FULL] -U (note, for me it didn't work via pipenv, it complained about the '-U' option)
- Generate a HTML view of the schema ontospy gendocs <location of bengSchema.ttl>, choosing option 2
- Determine essential basic information that would be needed for rights

**Comment by mwigham** [comment]
Thanks @wmelder. Sorry, I wasn't so clear in my explanation. The generation of the HTML view using ontospy wasn't a goal of this issue in itself, but simply a means to easily check the schema in the test plan. So Eduardo's code already fulfils the first criteria of this issue nicely.  Of course, we will need to develop its use further, but that will be something to work on as we further discuss and develop the schema, and see what our requirements are for visualising it. 

Determining the basic rights information is indeed something that needs a new issue, and is worth quite a substantial story all by itself...
