### ISSUE TITLE
Change the schema.org Classes for the catalogue data, so that we can better express the hierarchical catalogue structure.

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#134]
It seems to be that a NISV Program item from the DAAN catalogue gets modelled as a [CreativeWork](https://schema.org/CreativeWork), although it seems to be given a partOfSeries property, that is reserved to the [Episode](https://schema.org/Episode) Class.

`      "@id": "http://data.rdlabs.beeldengeluid.nl/resource/program/2101608170159644631",
      "@type": "https://schema.org/CreativeWork",
      "https://schema.org/partOfSeries": {
        "@id": "http://data.rdlabs.beeldengeluid.nl/resource/series/2101608030026649931"
      },`

So, more general, to be able to better represent the hierarchical concepts from the NISV Catalogue data:
- [ ] Represent a catalogue program/media item as an Episode.
- [x] Fragments/parts/segments of a (Program media item, which are called 'scene descriptions' in DAAN should be modelled to [Clip](https://schema.org/Clip). Hereby they can be attached to the Episode they belong to. Also, by having an identifier of their own, these Clips objects can be referred to (for example for openbeelden links #128 ).
- [x] Seasons should be modelled as [CreativeWorkSeason](https://schema.org/CreativeWorkSeason)
- [x] Series should be modelled as [CreativeWorkSeries](https://schema.org/CreativeWorkSeries) 
`NOTE: We might have to be more precise, whenever applicable: "Specific subtypes are available for describing TVSeries, RadioSeries, MovieSeries, BookSeries, Periodical and VideoGameSeries. In each case, the hasPart / isPartOf properties can be used to relate the CreativeWorkSeries to its parts. The general CreativeWorkSeries type serves largely just to organize these more specific and practical subtypes."`

![image](https://user-images.githubusercontent.com/1220375/129922066-ef56c170-d23f-460d-9842-81c1647cc8c2.png)

**Comment by wmelder** [comment]
@mwigham Could you please have a look at this issue? Based on comments in the code here: `src/models/SDORdfModel.py:30` I expect that this is something you have already thought about. What do you think about mapping the Classes slightly different? Do you think it is already possible to differentiate for Series? Etc.

Why a change? If we don't model Clip we can't get the scene descriptions in the LOD. The lod-importer currently gets its (aggregated program) identifiers from the aggregated index. If we want to include all items in the linked data (and we do want that) we also need to be able to get the other identifiers from the LOD and therefor we need Clips to be modelled and programs to change from CreativeWork to Episode. 
See this issue: https://github.com/beeldengeluid/lod-importer/issues/18

**Comment by mwigham** [comment]
@wmelder We already model CreativeWorkSeason, CreativeWorkSeries and Clip. So the only change would be the CreativeWork to Episode. My only reservation about doing that is that we also have items such as photographs and documents in the archive, so Episode is a bit too specific for our archive. What do you think?

**Comment by wmelder** [comment]
@mwigham 
It is kind of weird that these photographs are also indexed as 'aggregated_programs' and as program in the DM API. In some respect it would do justice to the assets if we would differentiate whenever we can, for example use https://schema.org/Photograph Class for photographs. We would have to implement more complicated code in the beng-lod-server though, which is less opportune.

But, on the other hand a generic Class like CreativeWork does fit all, and thereby makes it easier for us. The only thing is that partOfSeries, etc. aren't properties we can use then for programs. We can use the properties isPartOf/hasPart, which are also a bit more generic. 

About this note:
`NOTE: We might have to be more precise, whenever applicable: "Specific subtypes are available for describing TVSeries, RadioSeries, MovieSeries, BookSeries, Periodical and VideoGameSeries. In each case, the hasPart / isPartOf properties can be used to relate the CreativeWorkSeries to its parts. The general CreativeWorkSeries type serves largely just to organize these more specific and practical subtypes."`

This note suggests that it is better to diversify in Series type. But we can also say we want a simple and generic solution. If we choose not to model like TVSeries, etc. and map all series to CreativeWorkSeries we can use isPartOf/hasPart all the way from series (through season) through program to clips. That would at least allow us to capture everything we have in the archive in the LOD and keep it simple and use a consistent hierarchy (although not the most beautiful one in the world). 

So, this would mean we model it like this:
* stick with CreativeWork and not Episode, 
* use isPartOf/hasPart for all hierarchical relations,
* add scene descriptions as Clips to Programs using the hasPart property.

What do we do with CreativeWorkSeason that has a property partOfSeries with CreativeWorkSeries as range? Shall we also model this as isPartOf, just because that is more generic?

**Comment by wmelder** [comment]
@mwigham Indeed it seems that the types are already taken care of. My assumption was that we needed to add the scene descriptions as part of the programs in the LOD. But, apparently it works the other way around in the LOD server as scene descriptions seem to trigger addition of a hasPart property with the parent. But still the scene description needs to be captured using the ID. The relation to its parent will then end up in the triple store and we will able to query for children there.

Further, the aggregated_programs in de mediasuite index contain these scenedescription id's already. Therefor, I want to try to extract all the ID's (not only the program id's) from the aggregated_program metadata in a separate list. This only requires something more than the lod-importer currently does.

By the way, the DM API also seems to have a part that allows 'children of' to be extracted: `curl -X GET "http://acc-app-bng-01.beeldengeluid.nl:8101/storage/LOGTRACKITEM?program_ref_id=2101608170159181531&logtrack_type=scenedesc" -H "accept: application/json"`

This is an alternative way that I want to explore if the other thing is not working.

So I guess for now this issue can be put on hold. We will have to assess the consistency of the hierarchical relations later.

**Comment by wmelder** [comment]
@mwigham One thing we need to check is this:
```But, on the other hand a generic Class like CreativeWork does fit all, and thereby makes it easier for us. The only thing is that partOfSeries, etc. aren't properties we can use then for programs. We can use the properties isPartOf/hasPart, which are also a bit more generic.```
So, we haven't changed these properties and we need to check whether it works as it is in the data right now. I can imagine it is convenient if we add the hasPart-inverse for every isPartOf property.  This can be done by SPARQL update, no problem.
Right now, we still have isPartOfSeries, so isPartOf is not completely generic. Need to check out if this is a problem, or not.

**Comment by wmelder** [comment]
@mwigham  One thing that is not so strong in making the solution generic, is that you can now only indirectly derive the type of the catalogue item. And you need to have inside information on the data model. 

Maybe a way out is to add an additionalType indicating that a program is not only a sdo:CreativeWork, but also a nisv:Program? Or..?

**Comment by wmelder** [comment]
Inverse hierarchical logtrackitems relations are yet not available, e.g.:
```
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Select all logtrackitems that are scene description for a program
SELECT *
WHERE {
  VALUES ?program {
    <http://data.rdlabs.beeldengeluid.nl/id/program/2101608190180567031>
  }
  ?program rdf:type sdo:CreativeWork .
  ?program sdo:hasPart ?scene_description
 
} LIMIT 10
```
Do we need a SPARQL update query to fix that?

```
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# insert inverse relation for hierarchical relations
INSERT {
  GRAPH ?g {
		?scene_description sdo:isPartOf ?program
	}
}
WHERE {
  GRAPH ?g {
    ?program rdf:type sdo:CreativeWork .
    ?program sdo:hasPart ?scene_description
  }
} 
```

**Comment by mwigham** [comment]
@wmelder I agree it would be nicer to be specific about the types of items, but that requires a lot more intelligence in the code to correctly recognise those types. I think it is better to start for now with the generic solution, and then we can always add more specific later. As you suggest, we could do this nicely with additionalType without needing to change the basic model. 

What is the benefit in adding the inverse relations? You can always retrieve the scene descriptions with the correct query.

**Comment by wmelder** [comment]
```
What is the benefit in adding the inverse relations? You can always retrieve the scene descriptions with the correct query.
```

It might be easier to discover relations if the inverse relation is there, otherwise the user would have to find out it is missing and prepare the right query. 
For example, using SPARQL I tried to get all scene_descriptions that have isPartOf with particular program and got zero results. From the code I understood that the triple program_id hasPart scene_description_id was added to the scene_description (has_clip). After changing the query to hasPart I got results. Adding scene_description_id isPartOf program_id would enable discovery the other way around using SPARQL.

```
@wmelder I agree it would be nicer to be specific about the types of items, but that requires a lot more intelligence in the code to correctly recognise those types. I think it is better to start for now with the generic solution, and then we can always add more specific later. As you suggest, we could do this nicely with additionalType without needing to change the basic model.
```
Ok, then we leave it for now..
