### ISSUE TITLE
As a publisher of NISV RDF data for external parties, I want it to use unique, persistent identifiers that use a namespace that reflects the identity of NISV

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#14]
Internally for test purposes, we can use identifiers that are simply a namespace of our choice plus the program identifier. Once we publish the data, those identifiers should be globally unique, persistent, and use a namespace that makes it clear that the data is from NISV, preferably also that is consistent with how URLs are constructed for other uses by NISV. We have also previously discussed that we want the namespace to be understandable for a user and not too specifically connected to a certain technology/use of the data (for this reason we opted not to choose lod.beeldengeluid.nl)

**Comment by jblom** [comment]
@mwigham please put this as acceptance criterium in the story for creating the basic DAAN RDF. I'd say it's part of the basics of triple creation. If you agree please close this one

**Comment by mwigham** [comment]
Unique identifiers is part of the basics of triple creation, but choosing how we will create our NISV identifiers for external published linked data is another matter, as Willem mentioned in our discussion recently. That's why I have it as a separate issue, albeit one that we don't need to tackle until we're ready to publish externally.

**Comment by wmelder** [comment]
I guess this can be closed. 
What we have right now is:
- identifiers for SKOS Concept and SKOS COnceptScheme
-- http://data.beeldengeluid.nl/gtaa/{{ concept_notation|conceptScheme_name }}

* identifiers for dataset, datacatalog and datadownload
-- http://data.beeldengeluid.nl/id/{{ dataset|datacatalog|datadownload }}/{{ daan_id }}

* identifiers for cat items
-- http://data.beeldengeluid.nl/id/{{ program|series|season|scene }}/{{ daan_id }}

Together with the APIS domain this makes up our open data presence:
https://{{ cat|gtaa }}.apis.beeldengeluid.nl/{{ sparql|oai|search|autocomplete }}

The only thing is that we have to configure our web proxy. But I think we have a proper domain.

@mwigham Can you close this issue if you think it is OK?

**Comment by mwigham** [comment]
All seems fine, great that we have taken this step now!
