### ISSUE TITLE
Deploy a Comunica frontend that provides example SPARQL queries for the the catalogue

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#149]
- [x] Deploy a Comunica frontend instance {somewhere}
repo: https://github.com/beeldengeluid/comunica-web-client
web client: https://comunica-web-client.vercel.app/
- [x] Make sure example queries are loaded {see [here](https://github.com/beeldengeluid/beng-lod-server/blob/master/resource/example_queries.json)}
- [x] COnfigure it for the sparql endpoint [here](http://54.217.179.144/)
- [x] Test NISV example queries via [web client](https://comunica-web-client.vercel.app/)
- [x] Compare a bit with the yasgui (Willem): 
* a) query editing {autcomplete properties (from prefix.cc)}
* b) results, grid view, etc.

related Open Data lab stories:
https://github.com/beeldengeluid/opendatalab/issues/16
https://github.com/beeldengeluid/opendatalab/issues/9
https://github.com/beeldengeluid/opendatalab/issues/1

**Comment by phivk** [comment]
Thanks @wmelder, I previously made these issues as part of the [web client repo](https://github.com/beeldengeluid/comunica-web-client/)

- https://github.com/beeldengeluid/comunica-web-client/issues/1
- https://github.com/beeldengeluid/comunica-web-client/issues/2

I will keep both these issues in sync :)

**Comment by phivk** [comment]
I've now closed these issues as part of the [web client repo](https://github.com/beeldengeluid/comunica-web-client/):

- https://github.com/beeldengeluid/comunica-web-client/issues/1
- https://github.com/beeldengeluid/comunica-web-client/issues/2

see the results at:
https://comunica-web-client.vercel.app/

NB: endpoint at http://54.217.179.144/sparql is currently not working. Example queries should still be tested via web client before closing this issue.

**Comment by wmelder** [comment]
Martijn heeft het geregeld: https://cat.apis.beeldengeluid.nl/sparql
Willem Melder: met als bijeffect dat de redirect naar yasgui niet meer kan... :thumbsup: dus wel sparql endpoint, maar ook alleen dat...

**Comment by wmelder** [comment]
* de namen van de queries prefixen met “NISV ” zodat ze bij elkaar gesorteerd staan 
> hoeft dan niet als we maar één endpoint hebben
* queries verwijderen (kan jij ook, in de queries folder)
* endpoints verwijderen (kan jij ook, in settings.json) 
> alle endpoints er uit behalve NISV SPARQL
* kijken of het mogelijk is om NISV als default data source in te stellen, zodat die aan het begin wordt geladen 
> NISV_SPARQL als enige en dus ook default

**Comment by wmelder** [comment]
Voor wat betreft dit punt ```Compare a bit with the yasgui (Willem)```:

a) Comunica heeft een dropdown voor queries <-> yasgui meerdere tabbladen
b) Zowel comunica als Yasgui checken de query syntax (zelfde?)
c) Yasgui vult namespaces en properties aan met autcomplete properties van prefix.cc.
d) in Yasgui URI's in query results zijn clickable (comunica niet)
e) yasgui heeft results in grid view, comunica onder elkaar...
f) comunica heeft Graph-LD query interface

etc.?

**Comment by phivk** [comment]
@wmelder hoe belangrijk weeg jij de verschillen tussen Comunica en Yasgui?

Ik heb tot nu toe alleen Comunica gebruikt. Ik denk dat ik veel ga hebben aan de GraphQL-LD support wanneer ik dat zou gebruiken voor de integratie van de datasets...

**Comment by wmelder** [comment]
ik vind de results van yasgui handiger, maar comunica heeft weer graphQL-LD. Verder heeft yasgui property lookup in prefix.cc, wat een pré is. Gezien het feit dat jij vertrouwd bent met Comuica gaan we daarvoor
