### ISSUE TITLE
As a developer, I want to test out possible mappings with other ontologies

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#15]
- [ ] choose some interesting ontologies for mapping (see [document](https://docs.google.com/document/d/1I9XRgPhyO_b-HbLGKrRjgQahEsc4F35yj7h1iPFaBco/edit)
- [ ] For a number of example archive objects, map them to these ontologies and generate RDF data
- [ ] review the generated data to identify issues
- [ ] implement a minimalistic, but useful HTML page that makes identifying pros/cons of each mapping easier
- [ ] discuss potential uses for the different types of data (embedded in a website, in a system for exchanging info with broadcasters, linking with wikidata ...?)

**Comment by jblom** [comment]
@mwigham @wmelder Put this one in the icebox, since I'd say the base B&G schema is more important as a first LD practice.

**Comment by jblom** [comment]
@wmelder let's try to make this a simpler story that can be finished in a sprint

**Comment by wmelder** [comment]
make a new story on implementation schema.org mapping
@wmelder wmelder

**Comment by jblom** [comment]
@mwigham @wmelder closing this one, since it is a bit too ambitious for the short term. If you disagree, please reopen and refine this issue, so it is more likely to be worked on
