### ISSUE TITLE
Task: Ensure tests work under both unix and windows

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#154]
There are issues with the newer versions of python/rdflib that means tests that work under unix fail under windows and vice versa. We need to look into this and get the tests working for both systems.

E.g. https://githubmemory.com/repo/RDFLib/rdflib/issues/1430

If necessary we can write separate tests using the pytest skipif functionality, but it would be better to get one set that works for both if we can.

**Comment by jblom** [comment]
@mwigham ok so you both use python3.8 and it still fails under windows?

**Comment by mwigham** [comment]
that's correct

Op wo 3 nov. 2021 om 14:19 schreef Jaap Blom ***@***.***>:

**Comment by wmelder** [comment]
@mari I thought that the issue #1430 was fixed. Anyway, I just pushed new test that should work on both OS'es. Will ask you for a review in PR.

**Comment by wmelder** [comment]
Jaap wrote a new way of handling relative paths. There was a small bug with that, that is fixed in the latest PR merge to master... 
Please try if that works for you on windows ...

**Comment by mwigham** [comment]
The tests run fine now under windows once the paths in the settings and settings-example file have been modified.

**Comment by wmelder** [comment]
Great! Another step towards a more stable repo :-)
