### ISSUE TITLE
EPIC: LD importing pipeline connected with DAAN data

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#16]
After or during https://github.com/beeldengeluid/x-omgeving/issues/44 we should think about how to update the linked data pipeline, so it will be connected to the live DAAN data.

See [LOD pipeline](https://github.com/beeldengeluid/beng-lod-server/wiki/LOD-pipeline) in wiki for more details

**Context: current pipeline**
The current pipeline reads from the old OAI-PMH, uses XSLT to transform the data into RDF/XML,  and (also) creates SPARQL update queries to populate a Cliopatria & Virtuoso triplestore (running as a Docker container)

**Tasks**
- investigate available inputs for the pipeline:
    - the new aggregated index (yielded in epic 44) (at present we note this as a possibility but will not investigate it further)
    - a different subscriber to the backbone #50
    - the new OAI-PMH (only contains GPP data!) #54 
- determine the best possible input for the importing process #55 
- develop a new base schema based on the DAAN model #13 
- adapt the existing pipeline to use the new input & the new model (load it in a single base graph)
- think of the next steps, e.g. consider how to generate use-case specific (more light-weight) graphs

**Comment by mwigham** [comment]
Note: we are leaving the carriers (items) out of the triplestore at present, as they cause performance issues and it is unclear if they would ever be queried in a linked data use case. However, we should not exclude them from the lod server, as this doesn't cause performance issues, and it allows the metadata for the carriers to be retrieved via a URI, which is useful for e.g. Nanne

**Comment by wmelder** [comment]
https://github.com/beeldengeluid/opendatalab/issues/2#
