### ISSUE TITLE
For Podiumkunsten, we need to provide RDA via an endpoint

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#181]
https://podiumkunst.wikixl.nl/index.php/Hoofdpagina

Given we mapping, we need to decide whether it will be another 'profile'for the open data endpoint, or that it needs to be provided as an independent endpoint containing all metadata. This depends on the requirements (e.g. do we need to provide the contents of the National dans theatre as a singel endpoint or do we need to provide everything from DAAN?

**Comment by mwigham** [comment]
Changed the name to better reflect the content of the issue

**Comment by wmelder** [comment]
We do provide it now in Podiumkunsten:

https://podiumkunst.triply.cc/beeld-en-geluid/MOZ-Muziekopnamen-Zendgemachtigden-RDA

Anyone with login can now access the dataset. 

I guess we can close it now.
