### ISSUE TITLE
As ODL user I need better documentation on the B&G data model

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#187]
- [ ] Extract the code for Ontospy from the beng-lod server
- [x] Create a standalone component using Ontospy that can produce the schema documentation. [beng-lod-ontospy](https://github.com/beeldengeluid/beng-lod-ontospy)
- [ ] Make the static HTML ontology pages available to the beng-lod server (or...?).
- [ ] Make it part of the deploy that it is updated every time the beng-lod is re-reployed.
- [ ] Add the link to the schema documentation to the labs website

**Comment by KleinRana** [comment]
No longer needed if #188 done

**Comment by wmelder** [comment]
we implemented lod-view for documentation purposes. the schema.org model is nicely described on the web. we can assist users with custome queries. so... this ontology issue can be closed for now
