### ISSUE TITLE
[Task] write unit tests for the most important beng-lod-server functions

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#189]
Roadmap: https://docs.google.com/spreadsheets/d/1mun1uFaws5TBkb_fQmonxmGSWhIYsF5lg0Ffous0Nis/edit#gid=0&range=J24

**Comment by KleinRana** [comment]
@wmelder , @jblom zijn er nu unittests voor alle belangrijke functies en is dit bijgewerkt voor de status quo

**Comment by wmelder** [comment]
ik weet niet of alle belangrijke functies voorzien zijn... jaap heeft in #191 de basic functions gedaan...

**Comment by wmelder** [comment]
ik update in ieder geval wel de laatste dev branches met deze unittests.

**Comment by wmelder** [comment]
impressive list. Good remark that some of the code will disappear completely in the future design, from this repo at least.

**Comment by wmelder** [comment]
add more use cases for all return codes
