### ISSUE TITLE
add GTAA page lod view

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#206]
- [x] create GTAA adapter in the beng-lod-server
- [x] get the lod server triples for the SKOS resource
- [x] show page using standard resource.html template (mimic [this](https://lodview.it/lodview/?IRI=http://data.beeldengeluid.nl/gtaa/123456&sparql=https%3A%2F%2Fcat.apis.beeldengeluid.nl%2Fsparql&prefix=http%3A%2F%2Fdata.beeldengeluid.nl%2F))
- [x] make sure resource can be dereferenced in multiple formats (is currently not supported by service layer)
- [x] change the reverse proxy routing for GTAA concepts

**Comment by jblom** [comment]
Status update: the code for the HTML view was merged. Now we need to test a little bit on the acceptance server https://data.rdlabs.beeldengeluid.nl and then we can deploy it to production (after we make sure to update the reverse proxy for the GTAA endpoint). 

@wmelder do we need the multiple formats for closing this issue?

**Comment by wmelder** [comment]
> @wmelder do we need the multiple formats for closing this issue?

content negotiation is already in place

**Comment by wmelder** [comment]
only reverse proxy needs to be fixed after deploy

**Comment by wmelder** [comment]
it's all done
