### ISSUE TITLE
As a developer, I need to fix errors in how the LD is generated from the OAI-PMH that prevent us from testing out use cases

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#22]
For the problems listed here, we need to consider whether they prevent us from testing the use cases we want to try out for LD. If so, then we need to solve them in this issue. If not, then they can be postponed, as the move to DAAN will require changes to the mapping anyway, and these issues can then be included in that (for as far as they are still relevant to the new metadata model).

Problems:
## DATES
- [x] Dates are strings instead of xsd:dateTime literals
- [x] Datestamp is missing (e.g. 975145@program) (do we want this?) NO, it is just the date for the record in the OAI-PMH index. Has no other function than harvesting using from/until parameter selection

## PERSONS/ ENTITIES
- [x] cast, speakers, sponsors, contracctors, executives and funders are not being created as objects, their properties are directly linked to the programme e.g. 147265@program 
- [x] Nationality object is missing (e.g. 4861616@program)
- [x] personnames are simple strings instead of person objects - we need to have the most basic person information harmonised for all persons, so that we can generalise in searches
- [x] originalCreators are added as Creators

## OTHER
- [ ] Qualification object is empty (e.g. 5268418@program), sometimes only its child **bg:source** is mapped to **schema:source** (e.g. 128480@program), and sometimes there is an empty qualification object in the RDF where there is none in the ES (e.g. 5356704@program)
- [x] deprecatedKeyword** & **keywords** are merged into **schema:keyword**
- [ ]  **bg:availablecollections** (in ES) is flattened to **schema:collection**
- [ ] * **genres** and **museum-genres** are merged into **schema:genre**
- [x] **schema:isPartOfSeries** is missing (e.g. 439304@season, should point to series 379721) 
- [x] recordinglocations and locations are merged
- [x] 'schema' prefix gets easily confused with schema.org, change to something else (perhaps nisv?)

The [requirements document](https://docs.google.com/document/d/146v0ZtllenwX_W_1IQzpD2Bk528n25J3wdhRbBIhIbY/edit#heading=h.1ax7hxdbb3ou) can helping with determining priorities

**Comment by wmelder** [comment]
This issue can be postponed, because we are already testing the current triple store using the latest version of the schema.

**Comment by jblom** [comment]
@wmelder @mwigham please split this one up in achievable stories for (this) and/or other sprints

**Comment by wmelder** [comment]
discussed with Mari that persons and organisations will be subclasses of skos:concept, so that the data will be much more easy to use. schema and transformation adaptations are needed.

**Comment by wmelder** [comment]
except for some minor points the transformation is improved for NISV data
@mwigham: can you do a review on the schema? It is in the branch wm_schema_changes_...
You can run the the server and test some programs/seasons, etc.
So testplan:
* review scheme
* check the resulting data

**Comment by mwigham** [comment]
Great to see the various people and their roles now modelled the way we had worked out together, good work! Looking forward to trying it out with queries once we have more data.

During review, I found some issues:
Schema:
- hasSortDate should have dateTime as its range

Transform:
- Funder objects are not created (see e.g.  207485@program)
- Producer and Sponsor are missing a level, the label is set at the Producer/Sponsor level (EntityInRole), when it should belong to the Organisation
- Something is going wrong with Executives, the transform gives an object of type skos:prefLabel instead of an ActingEntity with a skos:prefLabel
- Nationality objects aren't created  (While looking at the schema.org mapping, I wondered if we can perhaps map Nationality objects as a sort of EntityInRole - they seem to only exist to link a nameless person from a certain country with a production via a certain role, so that would match quite well)
- Original Creators are mapped as Creators

Note: at present hasRecordinglocation links directly to a label, while hasLocation links to a Location. This was deliberate, as recording locations don't use a thesaurus and are very specific, but I wonder if it is perhaps confusing to users

For the rest, there are some issues in the exact names of relations, I'll create a story for going through and getting these all sorted out properly. 

Finally, the code is in Python2. It would be handy to update it to Python 3 (the code itself then only needs the following changes - replace 'from urllib import urlencode' with 'from urllib.parse import urlencode', replace iteritems -with items.

I don't think any of these points necessarily have to be resolved in this story - I'll leave it up to you if you prefer to tackle some of them already here, or create a new story.

**Comment by wmelder** [comment]
@mwigham 
Already deployed the version you reviewed. 
Will work on the bulleted remarks you make here and redeploy. 
Thanks for your python2 to 3 remarks. I will create an issue for that and do it with some next version.

**Comment by wmelder** [comment]
@mwigham new redeploy is done...

The things that were not done:

- [ ] Nationality objects aren't created (While looking at the schema.org mapping, I wondered if we can perhaps map Nationality objects as a sort of EntityInRole - they seem to only exist to link a nameless person from a certain country with a production via a certain role, so that would match quite well)

- [ ] Finally, the code is in Python2. It would be handy to update it to Python 3 (the code itself then only needs the following changes - replace 'from urllib import urlencode' with 'from urllib.parse import urlencode', replace iteritems -with items.

For the first, we need to discuss I think what to do with it. It's not completely clear to me how we could model a language as a role or tie a not controlled term to a skos concept.
For the second I will create an issue (that also involves writing unittests).

**Comment by jblom** [comment]
@wmelder ok thanks for the update. Saw the new issue as well. Agree the first point needs to be discussed first before turning it into an issue.

@mwigham and you can see if this issue can be closed at some point. Please let me know if I can also review something (with a modest test plan ;-) )

**Comment by mwigham** [comment]
Seems fine to me to close this. Further testing isn't feasible at the moment as Cliopatria is very slow (Willem, could this have to do with loading new data?), but Jaap, there will be good opportunities later to review, as we are developing this iteratively.

Regarding the Nationality issue, currently a Nationality object consists of a country (which in DAAN will come from the GTAA) and a role. So my suggestion is to model that as an EntityWithRole that does not specify an entity. E.g.:

_testProgramme hasNationalityInRole _:EnglishGuitarist
_:EnglishGuitarist hasRole "guitarist" ;
                            hasNationality gtaa:Groot-Brittannië .

**Comment by jblom** [comment]
@wmelder ok if you also think this is all done, close this one please

**Comment by wmelder** [comment]
@mwigham  cliopatria shouldn't be slow because of loading, because that will be done on a second instance. It seems the schema: prefix hasn't recovered (after restart). Could that be a problem?

**Comment by mwigham** [comment]
I can't imagine that causing the problem, but it could be a symptom of another problem. Do you have decent speed when you query in the Yasgui editor?

**Comment by wmelder** [comment]
it's weird. I only get 400 bad request. thought it was my client code yesterday, but now it seems a server problem.
