### ISSUE TITLE
As a developer, I need to upload generated RDF data to a triple store

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#23]
- [x] Data generated from OAI-PMH, including blank nodes, is available in a triple store with API for SPARQL queries available
- [x] on completion, notify the @jblom so he can also hook up the search API to the SPARQL end-point (and test out grlc as well)

**Comment by wmelder** [comment]
@jblom just a notification that the cliopatria triple store is loaded...
this issue is not in the current sprint, but blabla... just close it. ;-)
