### ISSUE TITLE
As a LD dev, I want to populate a triple store via SPARQL update, so I can easily sync the B&G LOD server with the triple store

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/beng-lod-server#25]

**Comment by wmelder** [comment]
@mwigham ... er zijn twee LOD endpoints:
Cliopatria: http://zorin.beeldengeluid.nl:3020
Virtuoso/:http://zorin.beeldengeluid.nl:8899
De eerste heeft al wat data, maar ik heb nog niet het schema in de juiste prefix.Je kunt er al wel even rondkijken.
De tweede lijkt nog wat problemen te hebben met de sparql update.
Voor beide werk ik nu aan het uploaden direct van de OAIPMH via sparql update.
De named graph waar ik alles in probeer te stoppen is: http://data.rdlabs.beeldengeluid.nl/lod/

**Comment by wmelder** [comment]
Je kunt de yasqui query editor gebruiken:
Deze query werkt bijvoorbeeld: 

> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
> PREFIX schema: <http://data.rdlabs.beeldengeluid.nl/schema/>
> SELECT * WHERE {
>   ?sub schema:id ?obj .
> }   
> LIMIT 10

**Comment by jblom** [comment]
@wmelder cool! I was already doubting if I should implement something "quick" for spinning up that container for @mwigham, but it seems you'll have some triples to query very soon? :-)

Oh yeah could you also check out my PR #26 ? I added sweet unit testsssss + that URL param for convenient testing (Accept type is used by "proper clients" I guess).

**Comment by jblom** [comment]
@wmelder de vishaken mistte in je query:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://data.rdlabs.beeldengeluid.nl/schema/>
SELECT * WHERE {
?sub schema:id ?obj .
}
LIMIT 10
```

En dit werk nu enkel op de cliopatria toch?

**Comment by wmelder** [comment]
ja, iets meer resultaten met schema:hasMainTitle...
maar wat je ziet is dat op een of andere manier alle data onder één resource is terecht gekomen..
moeten we toch weer even uitzoeken helaas...

**Comment by wmelder** [comment]
now data in the named graph is overwritten, while trying to load the schema in the named graph... ;-P
will fix it later..

**Comment by wmelder** [comment]
lijkt er op dat als je turtle serialization draait dat ie dan geen unieke blank node id's aanmaakt.  :-1:

**Comment by mwigham** [comment]
laat me het weten als ik iets kan doen om hiermee te helpen

**Comment by wmelder** [comment]
het lijkt er op dat cliopatira slechts één blank node id aanmaakt... de tweede keer dat ik dezelfde data laad wordt er weer ééntje aangemaakt _:genid1 en _:genid2

**Comment by mwigham** [comment]
Waarom is het Cliopatria die de nodes aanmaakt? Doe je niks meer met de XLST om RDF te maken?

**Comment by wmelder** [comment]
vanuit de graph (gevuld via OAIPMH/XSLT) doe serialilze in Turtle. Dan verdwijnen de blank node ID's, maar de Turtle syntax bevat [ ] die aangeven dat het om een blank node gaat. Omdat je naar de target graph laadt moet de rdf store zorgen dat er geen dubbele blank nodes in dezelfde graph staan. Cliopatria zou dus voor iedere resource met blank node id een unieke id aan moeten maken.

**Comment by wmelder** [comment]
as described in this document: https://www.w3.org/TR/turtle/#BNodes

**Comment by mwigham** [comment]
Ok, ik snap het. Als je al blank node IDs hebt, is het misschien een optie om de blank node label Turtle syntax te gebruiken? (alinea 2.6 in jouw link)

**Comment by wmelder** [comment]
de json-ld serializatie heeft die id's wel, maar ik gebruik nou juist turtle omdat die ze zo mooi verbergt..
ik zal eens kijken of sparql andere formaten aan kan, waar de id's wel expliciet in staan. maar dan nog: de rdf store is in charge om blank node id's te managen...

**Comment by wmelder** [comment]
PS virtuoso gaat ook lekker:
Virtuoso 42000 Error SR186:SECURITY: No permission to execute procedure DB.DBA.SPARQL_INSERT_CTOR_ACC with user ID 107, group ID 107
geen permissie :-1:

**Comment by mwigham** [comment]
SPARQL kan diverse andere formaten aan, maar je kunt ook al in turtle de blank node labels aangeven, dan hoort de triple store per unieke label een unieke ID te geven (dat is de theorie ;) )

**Comment by wmelder** [comment]
zo te zien is de sparql syntax onafhankelijk van de return formaten, maar lijkt het wel verdomd veel op turtle. vandaar de keuze. En blank nodes zou je dus in theorie niet expliciet hoeven mee te geven. https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#sparqlSyntax
Echter, ik ben bang dat de INSERT DATA constructie via sparql/update dermate uniek is dat ClioPatria daar niet geheel op ingericht is.

**Comment by wmelder** [comment]
uit 4.1.4: Blank nodes are indicated by either the label form, such as "_:abc", or the abbreviated form "[]".

**Comment by wmelder** [comment]
damn: https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#grammarBNodes

Blank nodes can not be used in:

in a SPARQL Update request.

**Comment by mwigham** [comment]
Maar dat gaat toch alleen om DELETE?  Of lees ik het verkeerd?

**Comment by wmelder** [comment]
oh ja, je leest het goed

**Comment by wmelder** [comment]
ha, jacco van ossenbruggen en jan wielemaker buigen zich er ook al over .. :+1:

**Comment by wmelder** [comment]
de virtuoso rdf store wordt nu volgeladen direct vanaf de oaipmh...
helaas is de query editor niet zo fijn als die van cliopatira, maar in ieder geval genereert ie nu blank nodes.. er kan gesparqled worden!

**Comment by jblom** [comment]
@wmelder joehoe!!!

**Comment by mwigham** [comment]
@wmelder fantastisch!  Nog een reden voor mij om snel beter te worden, dan kan ik het uitproberen

**Comment by wmelder** [comment]
https://github.com/jrvosse/ClioPatriaDocker/issues/1 
Voor cliopatria wachten op fix. Victor heeft de fout kunnen reproduceren. Jacco en Victor hebben Jan gevraagd om oplossing. Jan gaat er volgende week naar kijken.
Voor virtuoso zit er wat data in maar de importer is er op een fout in de transformatie uitgeknald.
- [ ] fix the XSLT for title

**Comment by jblom** [comment]
Note: TODO:
- [ ] fix the XSLT for title
- [ ] still need to upload all the data in both stores (Virtuoso, Cliopatria)
- [ ] @jwassenaarbg can review the code
- [ ] update the data book
- [ ] add a useful entry in the wiki

**Comment by wmelder** [comment]
found out cliopatria is not loading all the classes right. it seems carriers are attached to the wrong programs and the totals for program, seasons, etc. don't increase while loading... really weird. will create issue at cliopatria docker. in the meantime I switch back to loading virtuoso.

**Comment by jblom** [comment]
hmm wow, sounds pretty confusing. Curious to see what their answer to your issue report is.

**Comment by wmelder** [comment]
yeah, weird... small load on virtuoso shows completely different statistics:

type | callret-1
-- | --
http://data.rdlabs.beeldengeluid.nl/schema/Publication | 389
http://data.rdlabs.beeldengeluid.nl/schema/Season | 125
http://data.rdlabs.beeldengeluid.nl/schema/Carrier | 3560
http://data.rdlabs.beeldengeluid.nl/schema/Productioncountry | 124
http://data.rdlabs.beeldengeluid.nl/schema/Recording | 124
http://data.rdlabs.beeldengeluid.nl/schema/Context | 164
http://data.rdlabs.beeldengeluid.nl/schema/Program | 389
http://data.rdlabs.beeldengeluid.nl/schema/Language | 192
http://data.rdlabs.beeldengeluid.nl/schema/Segment | 626
http://data.rdlabs.beeldengeluid.nl/schema/Creator | 389
http://data.rdlabs.beeldengeluid.nl/schema/Title | 805
http://data.rdlabs.beeldengeluid.nl/schema/Producer | 216
http://data.rdlabs.beeldengeluid.nl/schema/Series | 12

**Comment by wmelder** [comment]
- ISSUE: possibly the size of the update query is too big ... the cliopatria server shows unexpected results, the virtuoso one returns a error message that the query is too big...
- SOLUTION: instead of loading 24 records at the same time using listrecords, I will rather try to load just 1 record at a time. For that, I need to query for listIdentifiers and then for each identifier getrecord... Alternatively, I might load each identifier directly from the beng-lod-server, that executes exactly the same transformation... hopefully this will solve problems with both rdf stores..
- NOTE: the alternative solution is more in line with the future Claas solution (transforming listidentifers to a sitemap), so I might fire this as the preferred solution.

**Comment by wmelder** [comment]
still working on these:
- [ ]  still need to upload all the data in both stores (Virtuoso, Cliopatria)
- [ ] @jwassenaarbg can review the code
- [ ] update the data book
- [ ] add a useful entry in the wiki

**Comment by jrvosse** [comment]
Hi Willem, all,

I still have the feeling your weird statistics are related to either an error in your data or to a bug in our sparql update implementation that is triggered by the use of the INSERT DATA statement.  We routinely load up to 50M-100M triples in cliopatria directly without problems. Did you try to load the RDF directly without using sparql update? Direct loading of all kind of weird RDF, big and small, with and without syntax errors, has been extensively tested in the lod laundromat project, so I would be surprised if that would go wrong on your data. iIf you can send us an example sparql update that fails to insert the correct triples, that would help a lot in the debugging. Success,
Jacco

**Comment by wmelder** [comment]
- [ ] prepare rdf files for INSERT DATA
- [ ] load in cliopatria
- [ ] compare statistics

**Comment by wmelder** [comment]
> an error in your data

it was indeed an error in our data. Thanks for posting your remark. It was a nice trigger to investigate the 'load local file' option, which gave us the proper error message.

**Comment by wmelder** [comment]
170M triples and counting...

**Comment by wmelder** [comment]
to be continued in story #27
