### ISSUE TITLE
As data engineer I need to load NISV on Virtuoso triple store

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#27]
done:
- [x] load the data in Cliopatria (running, 471,446,993 triples in total)
- [x] inspect the zorin server for resources absorbed by cliopatria. Docker supports a [command](https://docs.docker.com/engine/reference/commandline/stats/) for statistics on the container resources: 
When the Graph is clicked on Cliopatria (and the browse/list_classes part of the API is called), `docker stats reverent_tereshkova` CPU yanks into **100% CPU**, before the final internal server timeout returns 503.

`CONTAINER ID        NAME                  CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
51d06234eabb        reverent_tereshkova   100.25%             96.56GiB / 188.7GiB   51.17%              190GB / 2.4GB       181MB / 53.2MB      15
`
The memory resources don't seem to be limited:  **51.17%** seems reasonable.
All containers seem to be have an memory usage upper limit of **188.7GB**

- [x] make virtuoso use the /data/volumes/ location for data
- [x] make a small adaptation to the code to prevent virtuoso to time out. As is noticed, after some thousand or more requests response time are over 0.9 or more seconds, which is much more than the first hundred requests, that start from 0.06 seconds and up. Modification so that request that take more than 0.1 second will raise a sleeping time of 1 sec, so that the server can recover and prevent the timeout, and thus stopping of the import process.
- [x] make the data volume for cliopatria persistent: https://docs.docker.com/storage/volumes/ and make sure to create a volume in the right place on zorin: /data/volumes/nisv_cliopatria
- [x] find out why Cliopatria is not handling requests multi-core (list_graph causes one core to yank into the 100% until the server times out) Github issue [here](https://github.com/ClioPatria/ClioPatria/issues/63)

ongoing:
- [ ] load the data in Virtuoso (http://zorin.beeldengeluid.nl:8899/sparql) ==++ REALLY SLOW ++==

next:
- [ ] improve performance for loading triples in virtuoso
- [ ] write a testplan, so that @jwassenaarbg can review the code
- [x] add a useful entry in the wiki

**Comment by wmelder** [comment]
Suggest to put this issue on hold for now. First, create the new schema, import test sets in the cliopatria, then retry, eventually by falling back on loading triples from donwloaded Turtle files from Cliopatria. See issue #33

**Comment by mwigham** [comment]
Agreed,, a comparison of the triplestores can wait, it's more important to get on with test and development cycles to improve our schema and data

**Comment by wmelder** [comment]
close it for now
