### ISSUE TITLE
renew server certificate that is outdated since august 5

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#275]
@MartijnBNG Kun je please zsm het certificaat checken? 
Blijkbaar is het certificaat verlopen en kan de server niet geverifieerd worden. Bijv. https://data.beeldengeluid.nl/id/datadownload/0023

![image](https://user-images.githubusercontent.com/1220375/183885459-e397dbe2-a3a9-4e6f-b260-19898031c5bb.png)

**Comment by MartijnBNG** [comment]
Zoals ook op Slack gezegd:

> Dat is geen toeval 😄  Mijn monitoring gaf aan dat het fout ging bij Peertube, daar heb ik Frank van op de hoogte gesteld. We hebben ook gesproken over hoe wij dat doen, met LetsEncrypt. Frank is daar achteraan gegaan. Peertube had net als data.beeldengeluid die sectigo wildcard certificate, die dus pas geleden verlopen is. Die heb ik dus nu vervangen, en het zou niet meer moeten verlopen (en dus automatisch updaten). Ik heb gezocht, het blijkt ook fout te gaan met [apis.beeldengeluid.nl](http://apis.beeldengeluid.nl/), dus die heb ik ook gelijk gefixt

**Comment by MartijnBNG** [comment]
P.S.: ik heb ook gelijk monitoring toegevoegd voor die twee
