### ISSUE TITLE
As a LD user I need to experiment with queries to be able to gather requirements for future development

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#28]
In the shared document linked data use cases* we collect and discuss queries that are relevant to either the nature of the data (statistics, etc) and meaningful for users (e.g. can search for people using (part of) their name.
From experimenting with the queries we learn and distill requirements (either about the data or the data model/scheme). These requirements will be put in a document so we can conceive of future development.

PRODUCT
- [x]  requirements document for linked data use cases

[Loading RDF](https://docs.google.com/document/d/15ElworomPvVnWzUYubUc_PlB1Pv4UxFdXYH8ZFhAhHo/edit#heading=h.ewdx764rvtkw)

[Requirements document](https://docs.google.com/document/d/146v0ZtllenwX_W_1IQzpD2Bk528n25J3wdhRbBIhIbY/edit#heading=h.1ax7hxdbb3ou)

[Modelling options](https://docs.google.com/document/d/1P5HuMlzPyzUlDTbHaDOXeZ9jU3q82rnNjtM0OuecrkM/edit?usp=sharing)

**Comment by mwigham** [comment]
@wmelder can you review this please?

**Comment by wmelder** [comment]
- will start a new docker instance for cliopatria to load new version of the data
- decided to import parts of the catalog (small datasets) in separate named graphs for testing purposes (loading is such a drag). Initially we load 'polygoon/Hollands Nieuws' en 'TV/actualiteiten'
- discussed the person model to use and came up with a fresh EntityInRole class that solves all the problems (@mwigham will model it in protegé) 
- when the new scheme arrives, the XSLT shall be updated, so it reflects the new model
- for now carriers will be available in the LOD server (although this type of information is nog so informative for most use cases)
- exporting the data from the named graphs tot Turtle, so that it can be loaded in Virtuoso

**Comment by jblom** [comment]
@mwigham @wmelder for retrieving convenience: adding the reference to story #33 here, which you made based on your previous comment.
