### ISSUE TITLE
Bug: Blank nodes for roles have type Resource, instead of type Role or PerformanceRole

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#297]
Persons are linked to a programme via a role, which is a blank node. This should have type Role or PerformanceRole, however it has type Resource

**Comment by wmelder** [comment]
I think this was fixed earlier. Can you list some examples?

**Comment by wmelder** [comment]
for example: is this oké?
```sh
curl -v -L -H "Accept: application/n-triples" http://data.beeldengeluid.nl/id/program/2102203150335388131
```

**Comment by wmelder** [comment]
Ofcourse this is more readabel: 
```sh
curl -v -L -H "Accept: text/turtle" http://data.beeldengeluid.nl/id/program/2102203150335388131
```

**Comment by mwigham** [comment]
I fixed this in the pull request I submitted earlier today https://github.com/beeldengeluid/beng-lod-server/pull/302

**Comment by mwigham** [comment]
It is odd that it apparently works for the production version of the beng-lod-server, but not for the version in main, and also not in the triplestore

**Comment by wmelder** [comment]
I think the triple store is a little behind. It is strange the production version differs. Somehow it was fixed, but changes not pushed?

**Comment by mwigham** [comment]
Was a branch deployed perhaps?

**Comment by mwigham** [comment]
Works fine!
