### ISSUE TITLE
Inventory CC0 fields that we have not yet published that may be of interest for music

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#299]
- [ ] Look into [CC0 fields](https://docs.google.com/spreadsheets/d/1WnAo1r6UvslCKgpbHaAQZ6lpHL6uiTxcfWLGGI88km0/edit#gid=0) and identify fields of interest for music that are not yet published in the ODL linked data
- [ ] Look at other available DAAN fields to see if there is something we have not yet considered for CC0

Acceptance criteria:
- [ ] We have a list of interesting DAAN fields (CC0 and non-CC0) for music that are not yet published in the linked data

**Comment by mwigham** [comment]
Candidate CC0 fields:
- Thesaurus title (not of specific interest for music, but could this make matching easier??)
- Recording location (free text)
- Country (nationality of an unnamed performer)
- Music genre
- Event (I think only of interest within the Netherlands)
- Recording information (specific fields .editingdate, .date)
- Scene desc recording information .date field
- Scene desc Event (as Event)

Other candidate fields:
- Carrier information (carriertype (WAV enz.), category (e.g. Digital), materiaalsoort (e.g. vinyl)). Quite niche information
- Broadcast organisation
- Carrier sound recording (mono/stereo). Niche
- Carrier type (CD, magneetband etc.)
- Collection - partOfCatalogue (Handelsplaten, MOZ). Are these understandable for outsiders?

Potentially relevant fields not included:
- Award (barely filled in for music collections)
- Motivation for composition (as above)
- Recording information (as above, with exception of editingdate and date)
- Language  (barely filled in for music collections)
- Used footage (as above)
- Scene desc recording information (as above, with the exception of the .date field)
- Carrier collection title (internal information)
- Carrier sample rate (almost always 96kHz when filled in for music)
- Carrier sound type (technical, almost always either 2-kanalen or naald-mechanisch)
- Carrier speed (barely filled in for music collections)
- Carrier version  - raw/program material (technical)
- Collection - group, source (internal information)
- Live broadcast true/false (not often filled in)
- Recorded with audience (not often filled in)

Note: all carrier information would be at modelled at MediaObject level (AudioObject or VideoObject)

**Comment by wmelder** [comment]
@mwigham What's the status of this issue now that https://github.com/beeldengeluid/x-omgeving/issues/657 is closed?

**Comment by mwigham** [comment]
I think it can be closed. Most fields have now been added, we may refer back to this list at some point to add in others.
