### ISSUE TITLE
OAI2LOD solution with initial RDF Model + Schema (for B&G) 

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/beng-lod-server#3]
The focus for this epic is to produce an initial schema for NISV that models the existing structure in RDF, and a dump of data converted to RDF using that schema. The model and data are intended for evaluation and experimentation.  Neither will be published yet

# Products
- [x] OAI(or other format)2LOD server deployed at data.rdlabs.beeldengeluid.nl
- [x] Data model created for use with RDF

# Acceptance criteria
- [x] Initial schema is available on the test domain.
- [x] An initial representative sample set of the NISV data served on the OAI2LOD is expressed in the schema, that we then can used as our baseline for further refinements.
- [x] Make sure we can deploy the solution for usage on OAI-PMH data provider, both dereferencing (GetRecord) as bulk importing (ListRecords).
- [x] make sure we make the right choice for inverse properties/relations,(ike isPartOf, hasCarrier, etc.) 
- [x] make sure we have unique blank node id for Elements/Classes that will not be published independently (instead of minting URI's).
- [x] choose the right naming for properties, so that we do not mix things up (AnnotatableEntity).
- [x] Make sure that Properties can be used for multiple Classes (Program, Series, etc.), also when rdfs:Domain prohibits Multiple Domains.
- [x] document the infrastructure in the wiki
- [x] document a how to page

**Comment by mwigham** [comment]
Should we perhaps split this up into smaller issues?  Both in the interests of making it achieveable within a sprint, and in the interests of quickly making LD available for us to play with.

**Comment by jblom** [comment]
@mwigham sure, glad to take suggestions. Could you take part of this out and put it in a new story? Let me know, so we can both check it and put it in the backlog as two more achievable issues.

**Comment by jblom** [comment]
@wmelder let's prune this story to only talk about the deployment

**Comment by jblom** [comment]
@mwigham @wmelder I've converted this issue into an epic. Now I'm going to write a story about the deployment for myself (register data.rdlabs.beeldengeluid.nl + hook it up to puppet for deployment)

**Comment by mwigham** [comment]
moved some tasks to the #18 issue as they are related to testing the results

**Comment by jblom** [comment]
@mwigham ok check. Also I removed the "Help: requirements needed" label on both issues, since they are already in progress. As a reminder (to myself as well), please check if the requirements are clear before working on a story and/or remove the label if things are already well defined.

**Comment by mwigham** [comment]
For how to use the Linked data server, see https://github.com/beeldengeluid/beng-lod-server/wiki/OAI2LOD-server-Beeld-en-Geluid

**Comment by mwigham** [comment]
First attempt at some layperson-friendly documentation is on https://github.com/beeldengeluid/beng-lod-server/wiki  - please improve

**Comment by jblom** [comment]
@mwigham a nice start for humanssss. Can't wait to implement the initial HTML representations of our wonderful schemafied data to please the layhomosapiens even more.

**Comment by mwigham** [comment]
I've added inverse properties to the schema, but not for carrier, as carriers are going to be blank nodes. It seems to me that we only want inverse properties when the original property points to a class that has a URI. Alternative points of view welcome!

**Comment by jblom** [comment]
@mwigham not sure what inverse properties you use (parent/child?), but I'm not sure if using these is desired? Also what is the reason for adding inverse properties? Could you give an example?

What do you think of this? http://richard.cyganiak.de/blog/2006/06/an-rdf-design-pattern-inverse-property-labels/

**Comment by mwigham** [comment]
The only reason would be to make it easy to navigate between entities that are linked in the other direction, e.g. from information about a series to information about the episode. Depending on what we actually do with the RDF in the end, we may not need the inverse properties, in which case we should definitely remove them - I agree with the post about avoiding clutter. The inverse labels would be nice - unfortunately we can't do that as we have decided not to use OWL, but to stick to RDFS.

**Comment by jblom** [comment]
@mwigham ok clear. I think it depends a bit on the application if we need them. How about separating the inverse properties in a tiny add-on schema? Also when we are ready to put them in the triple store: we could simply store inverse properties in a separate graph, so we can compare disk space, performance very straighforward?

**Comment by mwigham** [comment]
I like the idea, keeps it nice and clear.

**Comment by jblom** [comment]
cool, in that case we can also think of other "smart" or generated (transitive) properties and try them out separate from the "core" as well. If we find that an inverse or whatever additional property is really useful, we can simply put it in the core.

**Comment by jblom** [comment]
@wmelder @mwigham could you please update this story? Either make it ready for review/QA or update the milestone in case you still need to work on this (in which case. Please comment on what still needs to be done for this story to be finished)

**Comment by wmelder** [comment]
@mari alles gefixed, please test
- [ ] all issues fixed

**Comment by mwigham** [comment]
Moved triplestore upload to [this issue](https://github.com/beeldengeluid/beng-lod-server/issues/23)
This issue is now complete, QA should be done by the tests in [this issue](https://github.com/beeldengeluid/beng-lod-server/issues/18)

**Comment by jblom** [comment]
@mwigham @wmelder I've done the QA via the tests mentioned in issue #18 

Closing this one, to avoid duplicity
