### ISSUE TITLE
As a data engineer I need to reload the NISV data using the updated RDF scheme

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#33]
* decided to import parts of the catalog (small datasets) in separate named graphs for testing purposes (loading is such a drag). Data can be inserted/dropped to another graph. Unfortunately, since the graph is so large (471M) copying to another already times out. Therefor, we need to find another strategy to: 

1. find the series identifier (from ES?), 
2. load the series using OAI-PMH/XSLT in the named graph, 
3. find the program identifiers that have isPartOfSeries with the required series (from ES), 
4. load the program metadata from the OAI-PMH/XSLT in the named graph,
5. find the segments that have a isPartOfProgram with one of the selected Programs (from ES), 
6. load the segments from OAI-PMH/XSLT in the named graph.

* for now carriers will be available in the LOD server (although this type of information is not so informative for most use cases) [OUTDATED]

**Acceptance criteria**
- [x] start a new docker instance for cliopatria to load new version of the data
       This raises some problems. The first load of the NISV is needed to get the proper program ID's for a catalog. Therefor, the default docker image can't be loaded, 'cause that uses the default port. Need to create a persisten storage volume, manage the user permissions for cliopatria. => SOLUTION: change the port in config (edit entrypoint.sh) and docker build. Further, a new docker Volume on the host system needs to be created to ensure that data survives reboot.
- [x] need to create a new class to import data based on some query from one triple store, loading dat from the beng-lod-server into another triple store, using a named-graph for each catalog. => created a branch that contains MSDataManagerLODCopyNamedGraph in repository labs-importer.
- [x] load 'polygoon/Hollands Nieuws' en 'TV/actualiteiten'
- [x] update the XSLT, so it reflects the new model
- [x] export the data from the named graphs tot Turtle, so that it can be loaded in Virtuoso

**Comment by wmelder** [comment]
There is a fix for the LOAD problem. To be able to use it, need to:
`update to the git version of SWI-Prolog and update ClioPatria to the latest git version.`

**Comment by wmelder** [comment]
after downloading the latest git version for SWI-Prolog, installing git-archive-all to include all the submodules in a tar ball, rebuilding the SWI-Prolog docker image locally, building the latest git version of the Cliopatria repo in a docker and bringing the server up... I can load multiple resources in a single graph... pfff amazing...

**Comment by jblom** [comment]
@wmelder good to hear haha

**Comment by wmelder** [comment]
- [ ] load 'polygoon/Hollands Nieuws' en 'TV/actualiteiten' [IN PROGRESS] This is a slow process. It started quick, but as the size of the graph grows, so do the load times. ow 4M triples in store and loading a new resource already takes 4 secs. About 100000 items to go, so... it will take another 111 hours at the current speed. And the speed will decrease as more triples are loaded. :-(

**Comment by wmelder** [comment]
- [ ] implement a thread pool, so the loading will be speeded up and uses multiple cores (one for each web request)

**Comment by jblom** [comment]
@wmelder please let me reviewwww

**Comment by wmelder** [comment]
- [ ] load 'polygoon/Hollands Nieuws' [IN PROGRESS] en 'TV/actualiteiten' [DONE - MISSING IDS] 
- [ ] export the data from the named graphs tot Turtle, so that it can be loaded in Virtuoso [IN PROGRESS]
- [ ] write a testplan for jaap
- [ ] implement a thread pool, so the loading will be speeded up and uses multiple cores (one for each web request) [MOVE TO OTHER ISSUE]
- [ ] reconsider importing carriers (meaning the LOD server should not present the Carrier information). The total amount of triples is slowing down load. Carriers consume the larger part and are not interesting from a linked data perspective. [MOVE TO OTHER ISSUE]

**Comment by jblom** [comment]
@wmelder please put a testplan here, so I can conveniently test this

**Comment by wmelder** [comment]
@jblom 

[28-08-2019] testplan for Jaap:
* checkout branch  'wm-lod-create-nisv-catalogs'
* brew yourself a pipenv with the Pipfile
* cd into src/
* copy the settings-example.py to settings.py, check out ["BG_CATALOGUE"]["LOD"].
* inspect the code from MSDataManagerLODCopyNamedGraph.py and the sparql Classes in MSDataManager/.
* inspect the 'older' code in MSDataManagerLOD.py

In case you want to load data: spawn your own container from https://github.com/jrvosse/ClioPatriaDocker or build your own Cliopatria instance. Edit the settings.py with your configuration for "CLIOPATRIA_TO". Make a note that you also need to edit the settings for "USER" and "PASSWORD". Determine what bg:catalog you want to load, edit and run.

NB Feels like this is not a really good testplan, but let me know if you need something more from me.

**Comment by wmelder** [comment]
Note that there is current development in a different branch that has python3 code, a different set of LODManager Classes for loading LOD, GTAA loading classes and partitioning into manageable sizes (sitemaps has a 50.000 limit)...
The new approach (to prevent loading from being terribly slow) is to load approx. 50000 items in a graph in memory, then serialize to turtle and continue doing this until all items are processed. The Turtle files are then to be concatenated and loaded in the linked data server.

**Comment by mwigham** [comment]
@wmelder which branch is the python 3 one please?

**Comment by wmelder** [comment]
Issue moved to [beeldengeluid/labs-importer #37](https://github.com/beeldengeluid/labs-importer/issues/37) via [**ZenHub**](https://www.zenhub.com/)
