### ISSUE TITLE
As a data engineer I need to change the RDF schema for improved Person/Role information

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#34]
- [x] change the scheme, so that it reflects the discussed person model to use including a fresh EntityInRole class that solves all the problems

**Comment by mwigham** [comment]
The schema has been changed and checked in to Github (in the lod-schema-development-mari branch). Documentation is provided [here](https://docs.google.com/document/d/1P5HuMlzPyzUlDTbHaDOXeZ9jU3q82rnNjtM0OuecrkM/edit#heading=h.v1k1huj19c15), once the schema is reasonably stable, we will move documentation to the wiki.  

@wmelder  can you review please?

**Comment by wmelder** [comment]
We are making nice progress. Some first remark (also added to the documentation)

ArchiveEntity is a bit confusing. It both superclasses persons (as in creators) and the intellectual entities (as in an audiovisual, complex creation). Ofcourse I'm an advocate for simplicity, but not oversimplification! Let's discuss to what extent we need to distinguish between Entities (like Person/Organisation), entities (intellectual, audiovisual creations, business objects) and entities (like Context, additional information or classifications like Genre).

**Comment by wmelder** [comment]
some more remarks on the nonproductionorganisation entity...

**Comment by wmelder** [comment]
Although you already investigated a lot, making a note here that with respect to the modelling of the Programs, Series, Carriers, etc.  we need to further inspect and freely reuse some of the ideas from

* [FRBR](http://vocab.org/frbr/core),
* [IFLA-LRM](https://www.ifla.org/files/assets/cataloguing/frbr-lrm/ifla-lrm-august-2017_rev201712.pdf), and
* [PREMIS-OWL](http://www.loc.gov/standards/premis/ontology/)
* [schema.org](https://schema.org/Clip)

It seems objects, events, persons, organisations, clips with associatedMedia, works (or endeavours) and manifestions, etc. are already extensively described.
We might reuse (parts of) these vocabularies. Since our iMMix model was freely derived from FRBR that might be an close match for the modelling.

**Comment by jblom** [comment]
@wmelder nice list, good to see your recommendations externalised :-)

**Comment by mwigham** [comment]
Good ideas, perhaps put them in a new issue? And please check if they are (adequately) included in [the overview of relevant schemas](https://docs.google.com/document/d/1I9XRgPhyO_b-HbLGKrRjgQahEsc4F35yj7h1iPFaBco/edit)

Just for clarity for others, we are sticking close to the iMMIx structure for our first schema.  But later on we want to map to external schemas to help others to use our data, and also look at how we can get more out of the data by moving away from the concrete implementation  of data storage at NISV in our schema, and more towards a model of the underlying concepts - e.g. blogs, tweets, TV programmes and radio programmes relating to Eenvandaag all have to do with the same Eenvandaag 'entity', despite being on different carriers and distribution channels.

**Comment by jblom** [comment]
@wmelder ok closing this one. Please draft a new story for the next updates to the schema
