### ISSUE TITLE
As a data user, I want the GTAA Persoonsnamen to be aligned with Discogs artists, so we have a better quality of person data for search

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#37]
The alignment will be performed by creating a strategy in SpinqueDesk. This will initially be used to match non-compliant GTAA Persoonsnamen with Discogs artists, but can later be used to match the compliant names, producing an alignment with Discogs that we can use to enrich the data

Acceptance criteria
- [x] Vincent, Tim and Jesse agree that strategy is acceptable
- [x] Strategy is documented
- [x] Alignment is recorded in the [wiki](https://github.com/beeldengeluid/beng-lod-server/wiki/Alignments-of-the-GTAA-with-other-thesauri-vocabularies)

**Comment by mwigham** [comment]
Scheduled work on the strategy is completed, work is now on hold until a meeting on 25th June.

**Comment by mwigham** [comment]
Review meeting moved to 8th July. Strategy is documented, will do screengrabs once it is reviewed and any additional work is completed.

**Comment by mwigham** [comment]
REview meeting completed, strategy approved in general, some additional work which is in new stories. I think we can close this issue.

**Comment by jblom** [comment]
@mwigham awesome. Closing
