### ISSUE TITLE
As a LOD user, I want the properties and classes in the data to use the same names as the schema

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#41]
The RDF that we generate from OAI-PMH uses names for the properties and classes that are derived from the OAI names. The RDF schema uses names for properties and classes that we have developed to both fit with RDF conventions, and provide user-understandable names. We need to change the data generation so that it will produce the same names as in the schema. E.g. nisv:description should be nisv:hasDescription, and dc:relation should be nisv:hasPortalLink. 

A few months back I had tried out a possible way of sorting this sort of name change using some basic rules and a mapping file (see lod-handler-development-mari). We need to look at the best way of easily renaming the properties.

**Comment by jblom** [comment]
@mwigham could you define a bit more precisely what properties/classes of what exact thing do not match some other exact thing? Could you also provide an example? 

Also this still relates to the old OAI-PMH endpoint right? So far you and @wmelder are not using the new OAI? (curious to hear about what you've investigated there)

Put this in the icebox for now.

**Comment by jblom** [comment]
actually kept it in Unapproved, so we first this one out a bit better

**Comment by mwigham** [comment]
I've updated the description. Yes, this is relating to the old OAI-PMH endpoint, but the same issue will exist when we get the new one, as that uses DAAN names. It is probably best therefore to wait with resolving this issue until we move to DAAN, otherwise we have to solve it twice.

**Comment by jblom** [comment]
@mwigham ok moved it to the icebox now. Later on it needs to be extended with specific acceptance criteria

**Comment by mwigham** [comment]
This issue is now redundant, as we are moving towards a link with DAAN for RDF, and both methods currently under consideration use the schema names directly.
