### ISSUE TITLE
Refactor beng-lod-server om triplestore te gebruiken ipv storage API

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#418]
Hangt af van succesvolle verplaatsen van mapping code naar lod-importer, en dat deze gedraaid is om de triplestore te vullen - KLAAR
Hangt af van issue https://github.com/beeldengeluid/lod-importer/issues/130

Taken:
- [x] Pas beng-lod-server aan te werken op triple store
- [ ] Haal storage API code eruit
- [x] Testen
- [ ] Deploy nieuwe beng-lod-server

Acceptatiecriteria:
- [ ] productie beng-lod-server draait succesvol op de triple store

**Comment by Veldhoen** [comment]
Na upgrade to new standards (

**Comment by wmelder** [comment]
TODO: te veel types voor sdo:Person en andere skos:Concepte: oplossen in deze branch of anders nieuwe issue
```json-ld
{
      "@id": "gtaa:259602",
      "@type": [
        "skos:Concept",
        "rdfs:Resource",
        "sdo:Person",
        "sdo:Thing"
      ],
      "sdo:additionalType": {
        "@id": "skos:Concept"
      },
      "skos:prefLabel": {
        "@language": "nl",
        "@value": "Prince Far I"
      }
    },
```
