### ISSUE TITLE
Implement move of mapping logic

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#421]
Deze issue wacht op het [opruimen van de lod-importer](https://github.com/beeldengeluid/lod-importer/pull/122)

Zie [Archimate model](https://drive.google.com/file/d/1U2M89SMNBZ4opXgiSjkMQizuLlbLZm8A/view?usp=drive_link)
- [x] Script maken die functies implementeert die niet worden gemigreerd
- [x] Andere code modules overzetten
- [x] Config aanpassen met nodige parameters
- [x] Testen schrijven 
- [x] Volledige import

Acceptatiecriteria
- [x] Volledige import is gedraaid

**Comment by mwigham** [comment]
@wmelder gaat deze draaien vanuit deze branch, op Zorin

**Comment by wmelder** [comment]
- [ ] uitzoeken waarom hij de import gestopt is (mogelijk ivm proxy debug)

**Comment by mwigham** [comment]
denk ik ook niet, want volgens de code wordt in dit geval dan None teruggegeven voor de link, en dat wordt netjes afgehandeld. Wel goed dat je het meldt, ik maak er even een issue voor om te kijken waarom dit gebeurt en of het gewoon zo is, of of er iets mis gaat met de link zoeken

**Comment by wmelder** [comment]
import is klaar. Ongeveer twee keer zo snel.
```sh
2023-10-12 22:31:48,363|INFO|1323083|LODFileWriterNISVCatFromOAI|<module>|327|Done. Total time: 2 days, 10 hours, 49 minutes and 37 seconds.
```
