### ISSUE TITLE
As a developer I need to upgrade the code to Python3 and write unittests

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#43]
Upgrade the code so it can run with Python3.

- [x] Finally, the code is in Python2. It would be handy to update it to Python 3 (the code itself then only needs the following changes - replace 'from urllib import urlencode' with 'from urllib.parse import urlencode', replace iteritems -with items.
- [x] write test cases

**Comment by jblom** [comment]
@wmelder moved this to the top of the backlog. Let me know if you need help with the unit tests. I can help you along the way (otherwise please check e.g. the search API for unit tests)

**Comment by wmelder** [comment]
- [ ] prepare the repository tests to be run using pipenv tun pytest tests/unit_tests

**Comment by wmelder** [comment]
- [ ] need to write fixtures and tests for data GTAA

**Comment by wmelder** [comment]
@jblom please review
- code is refactored, so the steps for transformation are more transparant
- NOTE: etree.tostring return bytes, use encoding="unicode" to get a string
- tests for the concept handler are added
- fixture for file:// resource are added.
- pipenv is used
- pre-commit uses pipenv run pytest
- when all is gooed => DEPLOY

**Comment by jblom** [comment]
@wmelder ok so I adapted the tests & code a bit, so the code does the exception handling and the tests merely check if the code returns proper error messages. It's deployed!
