### ISSUE TITLE
As a thesaurus owner, I want to get an overview of Discogs alignments, to evaluate their quality

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#45]
Tasks
- [x] Generate Excel with results of group/person detection via comma
- [x] Generate overview of matches with labels and album names (current options either with SpinqueDesk and Angular, or SpinqueDesk and an Excel export + script)
- [x] Make it possible to generate the overview for subsets of the results, e.g. names with initials, names matched with levenshtein, ambiguous matches

Acceptance criteria
- [ ] Tim and Vincent can use the information to assist in evaluating the alignments

**Comment by jblom** [comment]
@mwigham all clear, added it to the bottom of the backlog

**Comment by mwigham** [comment]
Added additional information to overviews

**Comment by jblom** [comment]
@mwigham please also put whatever you've learnt about aligning in the beng-lod wiki

**Comment by mwigham** [comment]
@jblom is [this](https://github.com/beeldengeluid/beng-lod-server/wiki/Alignments-of-the-GTAA-with-other-thesauri-vocabularies#method) the sort of thing you had in mind?

**Comment by jblom** [comment]
@mwigham certainly, great stuff

**Comment by mwigham** [comment]
@jblom I think this one can be closed, we have no further requests for improving the overview
