### ISSUE TITLE
As a data engineer, I need to add some additional options to the Discogs alignment strategy

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#46]
Tasks:
- [x] Use track information to also generate album-artist pairs where these don't explicitly exist
- [x] Look at how to choose between ambiguous matches (after they have been confirmed with albums) based on whether match is on main name or alternative name, with or without fingerprinting (this step may be outside of SpinqueDesk)
- [x] Incorporate the extra filter for person/group into the workflow so that e.g. 'orkest' names are not matched on (include most recent list from email exchange with music experts)
- [ ] Link in the album matches using 'contains' (**note** this caused problems for SpinqueDesk when I tried it, need to look at whether it can be solved and if the extra matches are worth it (are they good enough?)
- [x] Document changes
- [x] Make some screenshots of completed strategy (screenshots of Spinquedesk)

**Comment by jblom** [comment]
@mwigham about the last point: I guess those are screenshots of the Spinque desk? Moved this to the bottom of the backlog

**Comment by mwigham** [comment]
A method for handling ambiguity has been chosen and will be implemented in #49. Album name matches using 'contains' are not being included, as SpinqueDesk has problems with this block. The strategy has been documented [here](https://docs.google.com/document/d/1vbEnbzTdvWPqJlXyOMjnmHscqOxr_9ghz5l6o2FWIjk/edit?usp=sharing), with screenshots.

**Comment by jblom** [comment]
@mwigham ok looks like this issue has been dealt with properly. Closing it. Maybe later on someone can do an overall review of your work
