### ISSUE TITLE
As a thesaurus manager, I want to know if ambiguous matches can be automatically disambiguated

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#49]
When matching GTAA concepts to Discogs, some of the matches are ambiguous. Ambiguous matches whereby more than one GTAA concept matches one Discogs concept have to be disambiguated by hand, to determine if these concepts indeed refer to the same person. Ambiguous matches whereby one GTAA concept is matched to more than one Discogs concept can potentially be automatically disambiguated, by preferring matches based on the main Discogs name to those based on the alternative names (which are very varied and cause lots of false matches). 

Tasks:
- [x] Export a sample of ambiguous matches from SpinqueDesk (CSV)
- [x] Write a script to read in the ambiguous matches and disambiguate them
- [x] Use the same script for unambiguous matches to show if they were based on the main name or alternative names
- [x] Generate an overview of the choices made by the script
- [ ] Evaluate the performance of the script

Acceptance criteria
- [ ] The sample and overview make it possible to decide whether to use automatic disambiguation or not

**Comment by jblom** [comment]
@mwigham I've added this one to the backlog

**Comment by jblom** [comment]
@mwigham can this one be closed or otherwise reviewed?

**Comment by mwigham** [comment]
Closed, the information seems to be useful.
