### ISSUE TITLE
As a developer, I need to compare the OAI-PMH and backbone options for the LOD pipeline

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#55]
For generating LOD from DAAN, we have three options - OAI-PMH, backbone import and generation from the aggregated ES index. We have tested the first two options in other issues. Now, we need to compare them to find the advantages and disadvantages, to help in choosing which option is best, or whether we need both

Factors to consider include but are not limited to:
- Does it support both ad-hoc access to Linked Data resources (like the beng-lod-server does) and upload to a triple store? Does either option require extra complexity?
- How does it handle bulk import (such as the initial import)? How does it handle incremental updates?
- Can GTAA concepts be reconciled straightaway, or does this require an extra step?
- Is the output suitable for both general Linked Data users and the Media Suite? Can something be done to make it suitable?
- Performance issues
- Fit with other parts of the x-omgeving infrastructure

**Acceptance criteria**
- [ ] There is a document that clearly shows the relative advantages and disadvantages of these two options

Note that we will not necessarily make a choice yet between the two options, as further information about use cases may be required.

See [LOD pipelines](https://github.com/beeldengeluid/beng-lod-server/wiki/LOD-pipeline)

**Comment by mwigham** [comment]
@wmelder I've updated this epic and added new issues, and a wiki page (see the epic description) to reflect what we discussed about how we will evaluate and compare different options for the DAAN-LOD pipeline. Please have a look and see if this is also what you had in mind - feel free to add detail and explanations.

**Comment by jblom** [comment]
@jwassenaarbg & @wmelder should review this (and think along)

**Comment by mwigham** [comment]
Documentation is on the [wiki](https://github.com/beeldengeluid/beng-lod-server/wiki/Comparing-OAI-PMH-and-Backbone-Importer-for-DAAN-RDF-pipeline)

**Comment by mwigham** [comment]
@jwassenaarbg @wmelder could you look at what I've [done so far](https://github.com/beeldengeluid/beng-lod-server/wiki/Comparing-OAI-PMH-and-Backbone-Importer-for-DAAN-RDF-pipeline) please and let me know what other factors I should consider for a good comparison of the options?

**Comment by mwigham** [comment]
For review @jwassenaarbg @wmelder, please read the [comparison](https://github.com/beeldengeluid/beng-lod-server/wiki/Comparing-OAI-PMH-and-Backbone-Importer-for-DAAN-RDF-pipeline) and comment on:
- [ ] Do you agree with the content?
- [ ] Is anything missing that we can investigate at this stage?(i.e. without having concrete user applications to compare the options for)

**Comment by jblom** [comment]
@wmelder @jwassenaarbg just a reminder to review this for @mwigham and "the greater good!"

**Comment by wmelder** [comment]
@mwigham The initial comparison seems very reasonable!

These comparisons might be added:
* whether the required metadata is available for both options. For example, the subtitle information is not part of the OAI-PMH, but might be available from the backbone. Also, rights information might be available for DAAN backbone, but not (yet) in the OAI-PMH provider. 
* time it takes to complete the initial download for the catalogue. For iMMix data in RDF using OAI-PMH and beng-lod it is down to 4,5 days, while loading DAAN data from the backbone still takes 20 days. 

Might add some description for the comparison for 'Suitability for public LOD' on the publication interfaces and the proceses of filtering to make sure services are conforming with the business requirements.

**Comment by mwigham** [comment]
@wmelder we can't compare the 4.5 days to the 20 days, as the data we are loading from the backbone includes all the carriers and logtracks, which the iMMix data didn't have. As scene descriptions are (unfortunately) logtrack items, we can't just ignore logtrack items entirely. So both the beng-lod-server and the backbone importer would need to retrieve/receive logtrack items, check their type, and then ignore them if they are not scene descriptions. I'm not sure how the times would compare between the two when they 'ignore' messages. Is that something we should test in this issue?

**Comment by wmelder** [comment]
@mwigham comparison between initial load via OAI-PMH and backbone would be possible, wouldn't it? Maybe for the OAI-PMH option you would be able to skip the sets that aren't needed? For both an estimate in total loading time could be added. In case these values are very different, one option could be preferred over the other.

**Comment by mwigham** [comment]
@wmelder It's not possible to skip the sets in OAI-PMH, as the sets are not more specific than 'logtrack item', unfortunately. The difference in loading time therefore comes down to how quickly the two methods can skip messages. I could measure that in order to compare. Estimating the total loading time is difficult, as I don't know how many messages they would be receiving, and how many of those they would skip.

**Comment by wmelder** [comment]
@mwigham I guess it has to be a posteriori 'estimates' then... It would be good to have at least some indication what loading times to expect for each method.

**Comment by wmelder** [comment]
@mwigham Why does the table state that for both option reconciliation is necessary, while the DAAN data in fact contains the skos:notation value, so that URI's can be reconstructed?

**Comment by mwigham** [comment]
Reconciliation is performed as part of the method, as the comment indicates. So perhaps 'reconciliation' is not the appropriate term, what I mean here is that the GTAA URIs are used in the data.

**Comment by mwigham** [comment]
@wmelder Do you think we are likely to use OAI-PMH at some point?

**Comment by wmelder** [comment]
@mwigham I cannot foresee things completely.

Currently, for the NISV collection we are using a combination of: 
a) beng-lod-server wrapped around the Flexdatastore Direct Metadata API
b) lod-importer, to get a list of identifiers using the aggregated index that is connected to the flexDatastore backbone
c) docker-cliopatria, to load the saved triples and provide a sparql endpoint.

More info [here](https://github.com/beeldengeluid/lod-importer/wiki)

This setup seems to be working pretty well (has to be tested though). Therefore, at the moment we don't need the OAI-PMH endpoint. Earlier it has been said that we could not use the DM API at all, so then we would have a problem and would have to look for alternatives.

**Comment by mwigham** [comment]
Thanks @wmelder. I'll close this issue now as I think we will probably have a different set of circumstances by the time we look at making this decision again, so we should evaluate again at that point (referring of course to what we learned in this issue :) )
