### ISSUE TITLE
As an LOD engineer I need to safeguard the current OAI-PMH solution, because ti will be discontinued by the end of the year

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#59]
Today (30-10-2019) we found out the OAIPMH provider was shutdown.

It turns out sysadmin doesn't want the server to be operational after 31-12-2019 (so the a-team says), because of the Redhat 6 version. See [lifecycle](https://access.redhat.com/support/policy/updates/errata#Details) and [support for RHEL6](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates)

Therefor, because we're not done yet with working on the LOD for the iMMix database, we need a solution that prevents from being stressed out to harvest eveything before the end of the year.

- [x] We need a RHEL7 server, probably xeniaonatopp is suited.
- [x] We can copy the data directory to xeniaonatopp
- [x] We need to install the Elasticsearch 1 server on it.
- [x] we need the tomcat based oaiserver solution installed on the server.
- [x] we need to redirect the oaipmh endpoint to the new location. Or we need to redirect our scripts to the internal server.

Note: we might be able to use some ansible scripts for installation

**Comment by wmelder** [comment]
- [ ] make our version of the OAI-PMH the new backend for the beng-lod-server

**Comment by wmelder** [comment]
the beng-lod-server config now points at http://xeniaonatopp:8091 for the OAIPMH server and it returns the LOD for the resources

**Comment by jblom** [comment]
@wmelder yay it works. To wrap it up real nicely we should create a DNS entry for it (or reuse the old one). What do you think?
