### ISSUE TITLE
As a LD developer I need to properly finish the nice things we did with the schema and HTML representation

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#60]
- [x] Make sure the HTML representation is loaded dynamically, e.g. every time a new Turtle schema is chaked in or, every time the html-schema page is loaded. Maybe this can be done on commit?
- [x] As Eduardo's code is based on the iMMIx version of the schema, install ontospy pip install ontospy[FULL] -U (note, for me it didn't work via pipenv, it complained about the '-U' option)
- [x] Generate a HTML view of the schema ontospy gendocs <location of bengSchema.ttl>, choosing option 2
- [ ] Determine essential basic information that would be needed for rights

**Comment by wmelder** [comment]
http://data.rdlabs.beeldengeluid.nl/html-schema/ is already referring to the HTML schema eduardo created.

**Comment by wmelder** [comment]
@jblom even een vraagje voor jou als Flask guru :wink:... Als ik de html pages voor het schema in de beng-lod-server dynamisch laat genereren met [ontospy ](http://lambdamusic.github.io/Ontospy/)krijg ik een website met statische html en javascript (zie bijv. [hier](http://www.michelepasin.org/support/ontospy-examples/schema_org_topbraidttl/index.html)). Ik probeer deze vanuit de beng-lod-server te laten server op het pad /docs/. Flask, wat dynamische templates gebruikt, lijkt steeds het verkeerde pad naar de subpagina's te  gebruiken, welke alternatieve app.route ik ook probeer. Ik heb alle pagina's al naar één directory docs/ laten schrijven en een route gedefinieerd, die send-from_directory gebruikt naar die docs/ folder. 

Dit gebeurt er: De index.html bevat een (bootstrap) navbar en vanuit de index.hml kies ik een pagina entities-az.html. Het pad wordt dan docs/entities-az.html/ en het pad van alle static files (js) wordt dan vanuit daar gevormd, ook al maak ik een route in Flask waarbij het pad weer docs/static/ wordt. Ook het pad voor 'Statistics' wijst naar /docs/entities-az.html/statistics.html/ ipv naar docs/statistics.html. Hierna krijg je allerlei 404 errors.

Ik heb geen opties meer en verwacht dat ik er mee moet stoppen of de ontologie buiten Flask hosten (statische html via nginx of apache) of...?? De branch op de beng-lod-server is issue/#60-ontospy. Heb jij een idee voor een oplossing?

**Comment by wmelder** [comment]
@jblom show me your static tricks!

**Comment by jblom** [comment]
@wmelder ok show me where to look and I'll check it out and fix ittttt!

**Comment by jblom** [comment]
@wmelder ah see your comment now. WIll check it nowwww

**Comment by wmelder** [comment]
@jblom Great you looked into it... The home page already did seem to be shown properly, but it seems the entities-az.html page is still not ok. Does it look ok with you?

**Comment by jblom** [comment]
yes it works for me. Did you checkout your branch? Did not merge it with master.
<img width="1177" alt="Schermafbeelding 2020-04-16 om 19 35 01" src="https://user-images.githubusercontent.com/917310/79488069-74c7a480-8019-11ea-8e23-d03e788ce633.png">


<img width="960" alt="Schermafbeelding 2020-04-16 om 19 32 22" src="https://user-images.githubusercontent.com/917310/79488085-7c874900-8019-11ea-90eb-1415631b778d.png">

**Comment by wmelder** [comment]
@mwigham Could you have a look at:

-  the Ontospy-generated [documentation pages for the NISV scheme](http://data.rdlabs.beeldengeluid.nl/docs/)?

- the [HTML representation](http://data.rdlabs.beeldengeluid.nl/html-schema/) that Eduardo build?

Is there anything missing (except for the pages being available in Dutch) in the Ontospy representation that Eduardo's version does have?

What is your preferred documentation?

**Comment by mwigham** [comment]
@wmelder I've compared the two methods. What I miss in ontospy compared to Eduardo's code is:
- Dutch labels and descriptions (as you already mentioned)
- A list of the classes, their labels and their descriptions (so missing labels/descriptions are quickly spotted)
- The option to tailor the code, e.g. filtering out concepts, or making it possible to edit

The first two points are mainly important for internal review of the schema within Sound and Vision. We can find alternative ways of doing this, it doesn't have to be done in the same tool as publishing the schema (or perhaps there are still some options for this in ontospy?). Regarding the last point, the main reason to want to filter was that the schema had lots of fields that were not so relevant. I would suggest that we are better off fixing this in the schema itself, possibly having multiple versions or modules to hide away complexity from users who don't need it. Regarding editing the schema, while this was a suggestion when Eduardo built the code, I think we had decided in the team that this was not so desirable.

I would prefer the ontospy version, I think, as it also includes diagrams and inherited properties, and we don't have to maintain it ourselves. Does it appear that ontospy will be actively maintained by its creators?

**Comment by wmelder** [comment]
> A list of the classes, their labels and their descriptions (so missing labels/descriptions are quickly spotted).

Ontospy doesn't have this, but a list of classes/properties and their labels/description can be generated from the graph. 

> The first two points are mainly important for internal review of the schema within Sound and Vision. We can find alternative ways of doing this, it doesn't have to be done in the same tool as publishing the schema (or perhaps there are still some options for this in ontospy?)

Agree. No results when looking for 'language' in the code, so it doesn't appear to be a supported feature. Maybe feeding an all Dutch schema version would result in Dutch pages? Tha would be nice.

> Regarding editing the schema, while this was a suggestion when Eduardo built the code, I think we had decided in the team that this was not so desirable.

Yes, indeed. No editing.

> Regarding the last point, the main reason to want to filter was that the schema had lots of fields that were not so relevant. I would suggest that we are better off fixing this in the schema itself, possibly having multiple versions or modules to hide away complexity from users who don't need it.

Do you think that the current schema is too complex? Does it have fields that are not relevant? For what users? 

> I would prefer the ontospy version, I think, as it also includes diagrams and inherited properties, and we don't have to maintain it ourselves. Does it appear that ontospy will be actively maintained by its creators?

Good point. The community seems to be rather small. I have only noticed one developer. So I don't know what happens when package versions like bootstrap, rdflib or other become end-of life. It is written in Python natively, so of course we can do adjustments ourselves when necessary. Alternatively, there are a lot of tools out there, so we might pick another whenever we need one.
