### ISSUE TITLE
As a LD developer, I want to evaluate IMDB as a potential LD data source for the x-omgeving

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#61]
Acceptance criteria:
A document evaluating IMDB as potential source, including:
- [x] Persistence of identifiers
- [x] Terms and conditions of use
- [x] Functionality of API
- [x] Suitability of API for Termennetwerk
- [x] Suitability of API for Media Suite?

**Comment by mwigham** [comment]
[Document ](https://docs.google.com/document/d/1vQ_Ip39hrLvpDUqAK9e18C71iQbVqxTRckwxxNqL5cE/edit?usp=sharing) is completed, will ask Jesse for review

**Comment by jblom** [comment]
@mwigham any update on the review? Can we close?

**Comment by mwigham** [comment]
@jblom I have one additional action from the reviewer, hoping to do that this week

**Comment by mwigham** [comment]
Action complete, closing issue
