### ISSUE TITLE
As a LD developer, I want to extend the RDF schema with more metadata fields from DAAN

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#63]
There are some DAAN metadata fields that are not yet included in the RDF, that would be useful. These fields should be added to the schema and also to the mapping used to convert the schema to RDF

Tasks:
 - [ ] Investigate the potential fields and decide which should be added: string versions of duration fields, heritagerule (as alternative source for heritagecategory), asset.category, asset,materialType, depostatusexplanation, archivalstate, (dragvolgnummer, selectievolgnummer, sequencenumber), 
, publicationsgroup, thematicgroup, nisv.language
- [ ] Add the fields to the schema and the DAAN mapping
- [ ] Test with the backbone/OAI to see if the new fields are read in successfully

Acceptance criteria:
- [ ] The fields are present in the RDF generated for DAAN objects containing that field

NB: Rights-related metadata fields have their own issue, as they are quite complex

**Comment by mwigham** [comment]
Question is whether we already want to do this, or wait for reviewing the schema with a group - #4

**Comment by wmelder** [comment]
@mwigham suggestion: shall we issue a new ticket for every single field that we want to add, instead of this more general issue? Like we did for materialType, etc?

**Comment by mwigham** [comment]
Yes, let's do that, they we can add them according to demand
