### ISSUE TITLE
As an LD engineer, I want to try out RML as a mapping tool

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#64]
[RML](http://rml.io/) is a mapping library that can create RDF from various sources, such as JSON, XML and CSV, using the schema as input for the mapping. We want to try this out to see if it would be a useful part of our LOD pipeline.

 # Tasks
- [x] Install RML 
- [x] Create a mapping for a core subset of the DAAN RDF schema, for either XML or JSON
- [x] Test this mapping with input files (no live link to backbone or OAI)
- [x] Document the experience and any issues encountered - bugs, ease of use, accuracy of result, performance etc.

# Acceptance criteria
- [ ] Documentation on the wiki describing the findings and giving a clear go/no-go for further testing

If the experience is positive, then we will expand the trial and create stories for testing with other formats and with the full schema.

Background:
While reviewing the makeshift method used to obtain RDF from DAAN using our schema, Willem found [RML](http://rml.io/), a standard (in development) for generating RDF from various sources, including JSON, CSV and XML. Both @wmelder and Mari [investigated it further](https://docs.google.com/document/d/1M7f3PlkZuWovm3j-LVd_ME7N5sMkpBGqB3pa6kYfbmc/edit), and it looks potentially very interesting. It uses the schema as focus, improving reusability (and understandability) in mapping different types of data to the schema. It also has the ability to combine multiple types of sources, which is very relevant for the Media Suite (particularly given many collections have CSV exports), and also means we could mix and match Flex Store and OAI data to get exactly what we need. There are question marks however as to how this works in practice - the software seems to be secondary to the academic papers, and is in Java so we would need to see how we can call it from our code.

**Comment by mwigham** [comment]
The tests are documented on the [wiki](https://github.com/beeldengeluid/beng-lod-server/wiki/RML-mapper). @wmelder can you look and see if the findings are clear, and if you have additional questions to include in further tests?

**Comment by wmelder** [comment]
Thanks for looking into this @mwigham. By looking at your findings (I haven't installed the java code myself), it seems not opportune to proceed using RML as it is now. Unless the trouble we have to go through without RML is even bigger, it seems better to let it rest. For now.

**Comment by mwigham** [comment]
Thanks @wmelder. Just for the record, can you indicate which of the findings are most decisive for your conclusion?

**Comment by wmelder** [comment]
@mwigham The negative points in the list on the wiki give the idea that the product is not mature enough. Ofcourse, if your verdict on the software is that it is usable and reliable we still can use it. From your findings I got the idea RML seems promising, but the 'standard' (or at least the software) is not really living up to the expectations.

**Comment by mwigham** [comment]
@wmelder Yes, that is the impression I get at present, that it's a good standard and tool that need further development still. We could already work with it, but with certain difficulties. So if we find those difficulties more trouble than it is worth, then we should leave it for now. We can keep an eye on the development and pick it up later on.
