### ISSUE TITLE
As a linked data developer, I want to update the schema.org mapping for DAAN

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#69]
We have an [initial mapping](https://docs.google.com/document/d/1ujma9R8kq5X9M1pg-o-Hl8cv9rvtpHSwl3sFZ2ONPRU/edit) of the NISV schema to schema.org. This was created based on iMMIx, and so may need slight changes now that we are using DAAN data. It is expected that the larger part will remain the same, as the aim when creating the NISV schema was to abstract from the exact storage system details.

**Comment by wmelder** [comment]
@mwigham do you mind closing this one as well?

**Comment by mwigham** [comment]
yes, this is now duplicated by the new issues
