### ISSUE TITLE
EPIC: Linked data sandbox

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#7]
The aim of this epic is to make the iMMIx version of the NISV archive available as a linked data source for internal experimentation. 

Main goals:
- "proper" schema
- dereferenceable resources (within the beng network)
- Data is in triplestore and is searchable via a SPARQL endpoint (within the beng network)
- Data is available via the Media Suite Search API (in the test environment) (NB: The data will NOT yet be available in the Media Suite user interface)

The steps we foresee are:
* model the data coming out of the iMMix OAI-PMH
* publish the schema and the data on the beng-lod-server on the data.rdlabs.beeldengeluid.nl subdomain. (this enables access to specific programmes and other resources)
* upload the triples to a triple datastore with SPARQL endpoint (this enables searching the data)
* add the data as a source to the test version of the Search API
*  internal consults with stakeholders to assess the suitability of the model

Once this epic is achieved, we will have an experimental 'sandbox' of data that we can use to try out linked data applications in the Media Suite and in other software (e.g. Jupyter Notebooks).

We have chosen to use the iMMIx data and not yet the DAAN data, as development with the iMMIx data is closer to completion. We will then have a store that we can already use for experimentation while we complete development with the DAAN data. We will leave out the carrier information and also enrichments (ASR, face recognition etc.), as these present performance problems while also seeming less likely to be relevant to Linked Data use cases. In a future issue we will need to consider 1) whether this information is useful in a linked data context 2) how we would handle aspects such as copyright and privacy.

We have deliberately chosen not to make the linked data externally available, as this raises a host of issues relating to copyright and privacy, which are made additionally complex by the fact that the ownership of these rights is in dispute. We have chosen to focus Linked Data development on the Media Suite, where access rights have already been agreed. This has the additional advantage of providing the opportunity to develop and test focussed Linked Data use cases with an active user group.

**Comment by roelandordelman** [comment]
@wmelder @jblom kunnen jullie aan deze EPIC toevoegen waar het vanuit gebruikersperspectief concreet naar toe werkt? Kan een een concreet onderdeel van een keten richting een gebruiksdoel zijn. Linked Data Sandbox is een beetje vaag. Dank. (dit in kader van alle EPICS revisen)

**Comment by jblom** [comment]
@wmelder @mwigham probably also outdated? (please close if so)

**Comment by mwigham** [comment]
@jblom agree
