### ISSUE TITLE
As LD engineer, I want to experiment with using the object type to query Person and Place information

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#71]
We want to be able to search for all People (or all Place) entities related to a programme at the same time, despite these being divided over different properties (e.g. hasCreator, hasSpeaker). 

One option is to avoid the need to specify the property type by using the object type to query. Objects linked by person-related properties are defined as the object type Person, so we can search on that. This will be investigated in this story. The option of using inferencing will be investigated in another story (#47), as will the option of explicitly specifying the property relation (#29). A fourth option is to map the data to explicitly add the high-level relations to the data.

Tasks:
- [ ] Ensure that the object type information is available in the data (either explicitly in the data, or by using the GTAA schemes to check)
- [ ] Write a query that uses object type information to get all Person (Place) entitites related to a program
- [ ] Test the performance of this query

Acceptance criteria:
- [ ] It is clear whether the query works or not, and how long it takes to run

**Comment by wmelder** [comment]
This is the same as #29, which is done. Example queries are available in the branch grlc-api.
