### ISSUE TITLE
As a developer, I want to create an initial RDF schema for NISV data

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#8]
- [x] Generate RDF data from ES with an initial rough mapping
- [x] Upload this to Cliopatria and generate an initial schema
- [x] Refine this schema in Protege
- create superclasses to allow us to define domains for properties used by more than one class
- merge classes where possible and scrap classes containing only one property
- specify Literals as strings or numbers
- correct errors
- [x] check if schema contains all the metadata fields correctly

#Product
- [x] A basic schema that we can use for generating test data

**Comment by mwigham** [comment]
Look into personNames and names, how are we going to model these in a sensible and meaningful way? (without going so far as already doing the GTAA link)
Errors: isPartOf is incorrectly being modelled as a class instead of a property (needs a correction in the generating code), museum-names, museum-locations and museum-personnames are missing (probably not in data sample)

**Comment by mwigham** [comment]
Schema under development is [here](https://github.com/beeldengeluid/beng-triples/blob/schema-development/testSchema.ttl)

**Comment by mwigham** [comment]
Not sure what is best for review here, as properly reviewing this schema is the subject of a couple more issues. @wmelder , could you perhaps check it out and confirm it is readable please?

**Comment by jblom** [comment]
@mwigham nice to see this progresssss: also want to review this myself in the next sprint

**Comment by wmelder** [comment]
Inital commit of the LOD server is done, work from the beng-triples solution with added to this repository and after inital deployment we will stepwise refine our schema here.
