### ISSUE TITLE
As a developer I need to create an app in Flask for the politicus browser

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#82]
- [x] create app in flask
- [x] create initial HTML page with search bar
- [x] create a model for the app data (JSON)
- [x] link the search bar to the GTAA queries

**Comment by jblom** [comment]
@wmelder als je netjes de structuur van b.v. de beng-lod-server flask app overneemt, kunnen we het ook weer makkelijk met die poppenspeler installeren onder een subdomeintje van rdlabs
