### ISSUE TITLE
As developer I need to create the wikidata queries for the politics browser

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#83]
For the politics browser, we want to retrieve political information about a given person in the GTAA from wikidata.
Tasks:
- [x] create the wikidata queries
- [x] work out how to call wikidata from grlc (NOTE: query limits and requires token)
- [x] put the wikidata queries in grlc

Acceptance criteria
- [ ] The queries return the desired information about a person (where present), and run in grlc

**Comment by mwigham** [comment]
@wmelder I've limited this issue to the wikidata queries, as I think they already earn their own issue.

**Comment by wmelder** [comment]
prima

**Comment by mwigham** [comment]
Note: User-Agent (required for wikidata access) is [filled in automatically](https://sparqlwrapper.readthedocs.io/en/stable/SPARQLWrapper.Wrapper.html) by the SPARQLWrapper that we use to execute grlc queries. Should this not be enough, then we can set it when we create the SPARQLWrapper in SPARQLEndpointHandler

**Comment by wmelder** [comment]
@mwigham  don't understand. Are we using SPARQLWrapper to execute grlc queries? Grlc supposedly exposes these queris as REST API endpoints, so why use SPARQLWrapper?

**Comment by jblom** [comment]
@wmelder grlc only does this when you use the grcl webserver. We only use grlc to interface with the stored queries (list them & fetch them, but execute them ourselves)

**Comment by jblom** [comment]
@wmelder @mwigham it is of course possble to host a grlc server ourselves. That way the search API could interact with those APIs instead of executing the queries itself.

Something to think about

**Comment by wmelder** [comment]
Doesn't make sense for me to say we use grlc and in the meantime store, fetch and execute those queries ourselves. 

The whole idea of grlc is that using the syntax of SPARQL plus some extra features like sparql url, grlc prepares a complete REST API for you. Don't need to think about that ;-)

So, I was expecting indeed we ran a grlc server that serves us our queries. I don't know what it takes to provide that, but that's the way to go.

**Comment by jblom** [comment]
@wmelder maybe yes, I'm also pretty sure our code dates back from before grlc had this web server part.

Let's check this a bit more and talk about it, so we are also prepared for it when we'll do the grlc session (see mail)

**Comment by mwigham** [comment]
Definitely a good idea to look into what the pros and cons are of using a grlc server vs. grlc as a library. And also a good topic for the grlc session, particularly to check details such as if we can set things like User-Agent when using grlc as a server.

For now, I have created a query `getWDPoliticalInfoForPerson` which uses our current grlc implementation. This takes a gtaa identifier as input and retrieves the occupation, political party and ideology of the party for the person, if they are in WikiData and aligned to the GTAA. 

@wmelder can you try this out (on test) please and see if this is the sort of information you are interested in for the app? Is there more information we want (at this stage)? At the moment it picks up EN labels only, so for example for Arie Slob it misses his current function as that has no EN label. So we need to consider what we want to do in those cases. 

It is also pretty slow. That seems to be mostly grlc, as entering the queries in the wikidata query editor is reasonably quick.

By the way, there are 6693 politicians in wikidata with a link to the GTAA - quite a nice number to be going along with!

**Comment by wmelder** [comment]
@jblom I need this: https://search-test.rdlabs.beeldengeluid.nl/api/v1.1/lod/grlc/GH_USER/GH_REPO?at=JOUW_TOKEN&cid=JOUW_CLIENT_ID

**Comment by mwigham** [comment]
closing this, as the underlying code will be reviewed in #88
