### ISSUE TITLE
As developer I need to discuss and realize added value for Media Suite users

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/beng-lod-server#85]
- [ ] report on the usability of the politician browser 
* app vs notebook
* wikidata properties
* grlc queries (test, via search api, incl user-agent)
* field research (hoe doen anderen dit?)

- [ ] research how aggregate queries can be faster
* investigate elasticsearch equivalent queries
* e.g. virtuoso, neo4j

- [ ] discuss integration issues for the Media Suite

**Comment by wmelder** [comment]
Aggregate queries for subjects and politicians can be replaced with some QueryDSL instead of SPARQL and the replacement is much faster. The point is though, that the data itself is not referring to concepts (or concepts of persons) and thereby we miss the link with the outside world, the network of terms, the linked data cloud, etc, and any outside collections. Further, segments can contain subjects, we can query for that in ES, but it will only give results if we query the basic index not the aggregated index. So, the question is how segments are covered right now in the Media Suite and how is this compared to the ideal situation? Wouldn't it be nice to get the segments in return, not all the programs that contain the segments (as is the case in the aggregated index).
For integration in the Media Suite is the discussion planned for thursday 14 of August. It was prepared with a document by Mari
Ready to close this?

**Comment by mwigham** [comment]
Yes, fine to close this.

Which person/politician queries have you replaced with QueryDSL? As far as
subjects go, it's currently not such an issue to not have the concept IDs,
given we have no alignments and therefore no links to the outside world
(and this will most likely be challenging in the future too). But we
certainly need the IDs for persons.

Better support for segments would indeed be handy in the future

Op do 13 aug. 2020 om 00:49 schreef Willem Melder <notifications@github.com

**Comment by jblom** [comment]
@wmelder @mwigham the document is a nice result for this story, so indeed closing this. About searching for segments, we should investigate this separately in a dedicated story.
