### ISSUE TITLE
As a developer, I need to generate statistics about the political alignments represented by the persons in a set of programme search results

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#87]
Tasks:
- [x] Create a wikidata query to get all the possible political alignment
- [x] For a set of program IDs, get all the people in the programs
- [x] For each person, use the Wikidata grlc queries to get their political alignment
- [x] Create statistics for the set of results, including people who are not in wikidata, and people without an alignment
- [x] Test the code in a notebook

Acceptance criteria:
- [ ] The code creates the desired statistics and can be easily modified to work in the politician browser demo (Note: (pie) charts can be done in [Bootstrap](https://mdbootstrap.com/docs/jquery/javascript/charts/))

**Comment by mwigham** [comment]
The queries have been written and are in the sparq-queries repo, a demo notebook can be found [here](https://drive.google.com/file/d/1EQpA9RgMo4hj1LsfC_pxhrRi4X5ojtdR/view?usp=sharing). 

While working out the demo notebook, a number of questions arose that should be discussed with users at a later point:
- count number of persons or number of  appearances? 
- count people once per program, or does it count more if they had multiple roles in the program?
- only count people in certain roles? 
- what to do with ambiguous people? (> 1 alignment). 
- do we need to know if some programmes had no people listed? 
- should we filter for only people with job 'politician'?
- is it useful to distinguish between those people in wikidata without information about their alignment, and those not in wikidata? Or is it enough to know that the alignment is unknown?

Note: the demo notebook didn't use the 'all alignments' query, but this could be used if we wanted to always show all alignments, even if the program didn't contain any people with that alignment.

Currently the demo notebook makes the following choices:
- all roles are counted
- persons counted only once per program
- counts are made of persons and of appearances, can view both
- ambiguous people listed separately
- no info about programmes without persons
- politician not enforced, but must be  member of a  party to get an alignment
- 'unknown' and 'not in wikidata' are shown separately

Below are some examples for a set of 10 political programs:
![image](https://user-images.githubusercontent.com/38520885/85551067-e7f52480-b621-11ea-91ce-5e2bbe56c1c3.png)

![image](https://user-images.githubusercontent.com/38520885/85551103-f3485000-b621-11ea-9b37-4527aa794cc7.png)

Summary of persons:

Ton Elias 
	Jobs: journalist, columnist, politician
	Functions: member of the House of Representatives of the Netherlands
	Alignment: centre-right

Dirk Kuin 
	Jobs: journalist
	Functions: 
	Alignment: unknown

Pim van Galen 
	Jobs: journalist
	Functions: 
	Alignment: unknown

Ferry Mingelen 
	Jobs: presenter, journalist, television presenter
	Functions: 
	Alignment: unknown

Antonet Schep 
	Jobs: 
	Functions: 
	Alignment: Not in wikidata

Hugo Schneider 
	Jobs: 
	Functions: 
	Alignment: Not in wikidata

Joost Karhof 
	Jobs: journalist, television presenter
	Functions: 
	Alignment: unknown

Nirmala Rambocus 
	Jobs: politician
	Functions: member of the House of Representatives of the Netherlands
	Alignment: centre-right

Mark Rutte 
	Jobs: historian, politician, teacher
	Functions: member of the House of Representatives of the Netherlands, Prime Minister of the Netherlands
	Alignment: centre-right

Hannie Stuurman 
	Jobs: trade unionist, politician
	Functions: member of the House of Representatives of the Netherlands
	Alignment: centre-left

Peter Nieman 
	Jobs: 
	Functions: 
	Alignment: Not in wikidata

Fons de Poel 
	Jobs: presenter, journalist, television presenter
	Functions: 
	Alignment: unknown

Kees Sorgdrager 
	Jobs: journalist, television presenter
	Functions: 
	Alignment: unknown

Arthur (Prognose) Vierboom 
	Jobs: 
	Functions: 
	Alignment: Not in wikidata

Cees Gravendaal 
	Jobs: 
	Functions: 
	Alignment: Not in wikidata

**Comment by mwigham** [comment]
@wmelder is this enough for the politician browser for this version?

**Comment by wmelder** [comment]
yes, more than enough for now.
