### ISSUE TITLE
As a developer, I need to write grlc queries that make it possible to find GTAA persons meeting certain political criteria

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#88]
Currently, users can search for programmes with a certain person based on their name. They cannot find programs based on broader criteria, e.g. programmes with members of the political party CDA. A wikidata query that returns GTAA identifiers of persons meeting certain political criteria would make this possible.

Tasks:
 - [x] Write wikidata grlc queries to find GTAA identifiers of persons meeting certain political criteria - party, alignment etc.
- [x] Write nisv grlc queries to find programs containing these persons

Acceptance criteria:
- [ ] Programs can be found for persons with certain political characteristics

**Comment by mwigham** [comment]
@wmelder could you test this please?
Test plan:
- [ ] Check out grlc-caching-120 branch of labs-search-api
- [ ] Run this locally, and open the API page in your browser
- [ ] go to POST
​/api​/v1.1​/lod​/grlc​/{user}​/{repo}​/{query}​/, click on 'Try it out', and enter your ID and token (usual ones for the search API)
- [ ] Enter the following pairs of values for query and payload, and check that each one runs and returns results
* getWDPoliticalAlignments 
{
  "endpoint": "WIKIDATA-LD",
  "parameters": [
  ]
}
* getGTAAPersonsWithPoliticalAlignment {
  "endpoint": "WIKIDATA-LD",
  "parameters": [
{
"key":"alignment", "value": "http://www.wikidata.org/entity/Q76074"
}
  ]
}
Note: you can replace the alignment with any of the results from the previous query
* getProgramsForGTAAPersonWithFixedRoles
{
  "endpoint": "BENG-LD",
  "parameters": [
{
"key":"gtaaId", "value": "http://data.beeldengeluid.nl/gtaa/149017"
}
  ]
}
Note: you can replace the gtaaID with others, note that many will not return results, as they are only annotated on segment level 
* getWDPoliticalParties
{
  "endpoint": "WIKIDATA-LD",
  "parameters": [
  ]
}
* getGTAAPersonsWithPoliticalParty
{
  "endpoint": "WIKIDATA-LD",
  "parameters": [{"key":"politicalParty", "value":"http://www.wikidata.org/entity/Q667680"}
  ]
}
Note: you can replace the party with any of the results from the query above
- [ ] Give any suggestions for new or improved queries

**Comment by mwigham** [comment]
Here is an example for programs containing politicians from the VVD:
![image](https://user-images.githubusercontent.com/38520885/86577368-66cf5300-bf7a-11ea-9e07-534a1da83dca.png)
 and for extreme-right politicians:
![image](https://user-images.githubusercontent.com/38520885/86577419-7c447d00-bf7a-11ea-832b-60497902efae.png)

It is odd that so many titles are not present, I will create an issue to look into this.

**Comment by wmelder** [comment]
```
It is odd that so many titles are not present, I will create an issue to look into this.
```
I think I found (just slightly discovering this matter some time ago) that when a title is missing, the season or series title is a good alternative. Properly also a reason why they didn't provide a program title: via hierarchy the title is derived.

**Comment by mwigham** [comment]
This is certainly a good alternative when the program title is missing. If it turns out that is the case for these programs, then we can use the same procedure.

**Comment by jblom** [comment]
@wmelder @mwigham does this still need review from Willem?

**Comment by jblom** [comment]
@mwigham was this story written before Willem's remark? (concerning the missing titles): https://github.com/beeldengeluid/beng-lod-server/issues/89

**Comment by mwigham** [comment]
@jblom yes, it was. So that story will probably only require a quick check that this is indeed the reason for the missing titles, and a decision what the appropriate behaviour is for the API - i.e. get series titles in the same query or in a separate query.

Yes, this issues does still need review.

**Comment by wmelder** [comment]
Ik heb het testplan niet doorlopen, maar wel naar de titel issue gekeken: 
```
{
  "query": {
    "ids": {
      "type": "program_aggr",
      "values": [
        "4201246@program"
      ]
    }
  }
}
```
 en deze heeft inderdaad wel een serie titel. Het betreft de wereld draait door, dus duidelijk waarom de uitzending zelf geen titel heeft. Zowel season als series heeft een titel:
![image](https://user-images.githubusercontent.com/1220375/89273745-427d9980-d640-11ea-9c0d-1ce8cdaf88e5.png)
![image](https://user-images.githubusercontent.com/1220375/89273804-55906980-d640-11ea-805f-db719d1360a2.png)
Het programma met id 4198758 is ook dwdd

**Comment by mwigham** [comment]
Bedankt @wmelder , die issue heb ik ook in #89 bekeken en de issue gesloten

**Comment by wmelder** [comment]
@mwigham  
Ik heb geprobeerd de grlc-caching-120 branch uit te checken maar die bestaat niet (meer).
is het nog nodig dat ik het testplan doorloop of is deze story achterhaald?

**Comment by mwigham** [comment]
@willem The branch has since been merged, so you can test this on the master. Thanks!
