### ISSUE TITLE
As a developer, I need to create an initial data model for Persons for the new Person graph, so that we can store useful information about persons in the NISV archive

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#91]
Tasks:
- [x] Select useful properties from schema.org for modelling a person
- [x] Create and document a model that combines wikidata, GTAA and archive person information

Acceptance criteria: the model stores all the information needed for the v1.0 LD person functionality

Note: As we try the model out we will improve it. We will also extend it with more information. At a later stage, once we are happy with how it functions, we will consult with metadata experts and possibly RDF experts to see if we can improve it syntactically and semantically

**Comment by mwigham** [comment]
The suggested model is in [this spreadsheet](https://docs.google.com/spreadsheets/d/1ELAOYEK6rAPnDTbOpricTKNmTXN1lRZxjI59ehcb7xg/edit?usp=sharing), with some notes about (temporary) design decisions

I suggest that we store the triples from wikidata in a separate graph (we already store the triples from the GTAA in their own graph) and that we select values from wikidata/GTAA to write to the person graph using schema.org properties. E.g. schema:description can contain the skos:scopeNote from the GTAA, or the schema:description from wikidata. By storing the original triples we make it possible to query a value from a specific source if we want, and we make it transparent where the data comes from. By copying selected information to a combined person graph we avoid issues with missing data and duplicated/conflicting values.

Here is an example, for Mies Bouwman (done manually so there can be some mistakes):

```
bengPerson:sd123 a schema:Person;
	schema:givenName "Mies";
	schema:familyName "Bouwman";
	schema:name "Mies Bouwman";
	schema:alternateName "M.A. Bouwman";
	schema:alternateName "Marie Antoinette Bouwman";
	schema:alternateName "Mies Bouwman";
	schema:description "Dutch television presenter";
	schema:gender "female";
	schema:birthDate "31 December 1929";
	schema:birthPlace "Amsterdam";
	schema:deathDate "26 February 2018";
	schema:deathPlace "Elst, Utrecht";
	schema:hasOccupation "television presenter";
	schema:hasOccupation "actor";
	schema:nationality "Kingdom of the Netherlands";
	schema:image "https://commons.wikimedia.org/wiki/File:NOS_televisieprogramma_Europaquiz._Mies_Bouwman,_Bestanddeelnr_930-2994.jpg";
	schema:isRelatedTo "Timp, Mies";
	schema:sameAs wd:Q426489 ;
	schema:sameAs gtaa:85227 .
gtaa:85227 a skos:Concept;
	skos:prefLabel "Bouwman, Mies";
	skos:hiddenLabel "Mies Bouwman";
	skos:scopeNote "tv-presentatrice";
	skos:related gtaa:254143 .
wd:Q426489 rdfs:label "Mies Bouwman";
	wdt:P735 "Mies";
	wdt:P734 "Bouwman";
	skos:altLabel "M.A. Bouwman";
	skos:altLabel "Marie Antoinette Bouwman";
	skos:altLabel "Mies Bouwman";
	schema:description "Dutch television presenter";
	wdt:P21 "female";
	wdt:P569 "31 December 1929";
	wdt:P19 "Amsterdam";
	wdt:P570 "26 February 2018";
	wdt:P20 "Elst, Utrecht";
	wdt:P106 "television presenter";
	wdt:P106 "actor";
	wdt:P27 "Kingdom of the Netherlands";
	wdt:P18 "https://commons.wikimedia.org/wiki/File:NOS_televisieprogramma_Europaquiz._Mies_Bouwman,_Bestanddeelnr_930-2994.jpg";
```

**Comment by mwigham** [comment]
@wmelder I suggest we defer a proper review for later as this will most likely get changed as we experiment. But if you have a moment to look and see if there is anything that is obviously a bad idea, then that would be great please.

**Comment by wmelder** [comment]
I do think it is beneficial for us to use schema.org, but we would mutually benefit (Wikidata and us) if we would start reusing and creating ontology alignments for Wikidata and schema.org. 

For example this property https://www.wikidata.org/wiki/Property:P106 (the occupation) has an equivalent property https://www.wikidata.org/wiki/Property:P1628 referring to https://schema.org/hasOccupation.

So, by adding the more structural information from the Wikidata Ontology graph, by re-using the equivalent property relations and by creating equivalent property relations in Wikidata where we miss some, we wil serve our case, but we will also contribute to the Wikimedia open infrastructure and serve the community (and thereby other heritage institutions). What is also a benefit for this is that we don't have to copy data.

Practicaly, I think this means we need to have four graphs in our rdf store: GTAA/Persoonsnamen, Wikidata, Wikidata Ontology and Schema.org ontology. This way, we will be able to write SPARQL queries querying for schema.org, while underwater, it is written as wikidata properties and values.

**Comment by mwigham** [comment]
Alignments between wikidata and schema.org are definitely very useful to
the community, but hasn't someone else done this?
I'd be happy to try this out and check how it performs. My only concern is
that we then don't have a way of preferring sources, we then get the
equivalent property from every source and so we get duplicates. Do you have
any thoughts about how we could handle that?

Op ma 12 okt. 2020 om 11:02 schreef Willem Melder <notifications@github.com

**Comment by mwigham** [comment]
Just had a thought, we could combine the two approaches. Copy a selected
set of values from gtaa and wikidata using explicit schema.org properties,
and also store the alignments. Then a query on just schema.org properties
will retrieve the curated set, while a query using inference or
specifying subPropertyOf will retrieve values from all equivalent
properties. What do you think?

Op di 13 okt. 2020 om 08:26 schreef Mari Wigham <mwigham@beeldengeluid.nl>:

**Comment by wmelder** [comment]
I was thinking just to store the wikidata properties. These have the equivalentProperty and thus using a propertypath you could query for a triple pattern like: some_wd_item wd:equivalentProperty/schema:hasOccupation some_wd_value, being exactly the same as some_wd_item wd:P106 some_wd_value

**Comment by mwigham** [comment]
That would be possible, but then we limit ourselves to only those GTAA
persons with a Wikidata alignment, which is only 35,000. It seems a bit of
a shame to miss out on the information in the GTAA itself.

Op di 13 okt. 2020 om 08:50 schreef Willem Melder <notifications@github.com

**Comment by wmelder** [comment]
@mwigham After discussing this yesterday, I think it can be closed now.
