### ISSUE TITLE
As a Media Suite user, I want the person autocomplete function to be reliable, so that I can use it for a high percentage of the time

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/beng-lod-server#96]
Currently we use the OpenSKOS autocomplete API for the person autocomplete function. This has become unreliable. To replace it, we will create our own autocomplete service, probably based on an ES index containing a copy of the thesaurus.

I expect that we will create separate issues for some of these tasks
Tasks:
- [x] Discuss if the ES index is the best option
- [x] Check the age of the current GTAA in the production cluster - March 2018. If this is recent enough, copy it to the test cluster. 
- [x] If the current GTAA index is too old, import a new copy (potentially make this a separate issue if we want a quick release of the functionality)
- [x] Create an API for autocomplete (via SearchAPI?)
- [x] Modify the autocomplete in the Media Suite to use the new API
- [ ] Create a separate issue for regularly updating the thesaurus (this is not a dependency for this issue)

Depending on user feedback, we can create an issue to fine-tune the autocomplete functionality, as we will then have control over it ourselves.

**Comment by mwigham** [comment]
@jblom and I will discuss how to approach this in a hangout

**Comment by mwigham** [comment]
@jblom I've looked at this, and my suggested approach is:
- Create a GTAA Person names index on the test cluster with fresh data from the thesaurus (I've asked Willem for the code he used to create the old index)
- Create an autocomplete endpoint in the Search API (in layered search? or basic search?)
- Call this via ExternalAPI (to keep in line with the other autocomplete functionality)

I'm a little in doubt as to whether to try out the [ES Completion Suggester](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-completion.html) straightaway, or whether to save this for eventual improvements later. On the one hand it's appealing to index suggestions in one go together with the rest of the data rather than have to re-index later. On the other hand it will take longer to work out how to use it, and I can already produce 'suggestions' by just querying the GTAA in ES that compare favourably with the current OpenSKOS service in terms of speed and quality. What do you think?

**Comment by mwigham** [comment]
@jblom do you perhaps have time to take a quick look at the way I've implemented this in the search API please? Branch 96-local-autocomplete. You don't need to test the code, just look at how it's set up. Once I've made any changes that you suggest then I will put this issue into review with a test plan. 

I first made an endpoint that could autocomplete from any index. Then I realised we probably don't want that as we would have to specify the index in the front end, so I made an endpoint that autocompletes from the GTAA, the location of which is specified in the search API settings. I have left the first endpoint in place as I thought it might come in handy at some point, but we can also remove it.

The code to call the API is in GTAALocal in the clariah-mediasuite project (branch 96-local-autocomplete). I kept very close to the OpenSKOS example, so there shouldn't be anything too odd there. The only thing I wondered was whether the fields for autocomplete (which are now specified in GTAALocal) should perhaps be moved to a GTAAConfig?

**Comment by jblom** [comment]
@mwigham I tested your `96-local-autocomplete` branches and everything works. I scanned the code and it seems quite lean  and to the point, so I do not expect to need a lot of time wrapping up the "local autocomplete" stuff. Oh and I merged the master code in all `96-local-autocomplete` branches, so it is up-to-date with Johannes & my revamp of the labo/search mappings

**Comment by mwigham** [comment]
Great, thanks!

**Comment by mwigham** [comment]
closing this as the code has now been released
